// 秘術士靈能戒律／天賦及其選項名稱
export default {
"Adaptive Body":"適應之軀","Environmental Adaptation":"環境適應","Adaptive Shield":"適應護盾","Energy Adaptation":"能量適應","Energy Immunity":"能量免疫",
"Aura Sight":"靈光視覺","Assess Foe":"評估敵人","Read Moods":"讀取情緒","View Aura":"觀察靈光","Perceive the Unseen":"察覺無形",
"Beacon":"信標","Bestial Form":"野獸形態","Bestial Claws":"野獸之爪","Bestial Transformation":"野獸變身","Amphibious":"兩棲","Climbing":"攀爬","Flight":"飛行","Keen Senses":"敏銳感官","Perfect Senses":"完美感官","Swimming":"游泳","Tough Hide":"堅韌獸皮",
"Blade Meld":"刃身合一","Blind Spot":"盲點","Brute Force":"蠻力","Brute Strike":"蠻力打擊","Knock Back":"擊退","Mighty Leap":"強力跳躍","Feat of Strength":"力量壯舉",
"Celerity":"迅捷","Rapid Step":"疾步","Agile Defense":"靈巧防禦","Blur of Motion":"殘影","Surge of Speed":"速度湧現","Surge of Action":"行動湧現",
"Corrosive Metabolism":"腐蝕代謝","Corrosive Touch":"腐蝕之觸","Venom Strike":"毒液打擊","Acid Spray":"強酸噴濺","Breath of the Black Dragon":"黑龍之息","Breath of the Green Dragon":"綠龍之息",
"Crown of Despair":"絕望之冠","Crowned in Sorrow":"悲傷加冕","Call to Inaction":"怠惰召喚","Visions of Despair":"絕望幻象","Dolorous Mind":"悲苦心智",
"Crown of Disgust":"厭惡之冠","Eye of Horror":"恐怖之眼","Wall of Repulsion":"排斥之牆","Visions of Disgust":"厭惡幻象","World of Horror":"恐怖世界",
"Crown of Rage":"狂怒之冠","Primal Fury":"原始狂怒","Fighting Words":"挑釁之言","Mindless Courage":"無腦勇氣","Punishing Fury":"懲罰狂怒",
"Delusion":"妄想","Diminution":"縮小","Miniature Form":"微縮形態","Toppling Shift":"絆倒轉移","Sudden Shift":"突然轉移","Microscopic Form":"微觀形態","Energy Beam":"能量光束",
"Giant Growth":"巨人成長","Ogre Form":"食人魔形態","Giant Form":"巨人形態",
"Intellect Fortress":"智識堡壘","Psychic Backlash":"心靈反衝","Psychic Parry":"心靈格擋","Psychic Redoubt":"心靈堡壘",
"Iron Durability":"鋼鐵耐久","Iron Hide":"鋼鐵之膚","Steel Hide":"精鋼之膚","Iron Resistance":"鋼鐵抗性","Light Step":"輕步",
"Mantle of Awe":"敬畏斗篷","Charming Presence":"魅惑存在","Center of Attention":"眾人焦點","Invoke Awe":"喚起敬畏",
"Mantle of Command":"統御斗篷","Coordinated Movement":"協同移動","Commander's Sight":"指揮官之眼","Command to Strike":"攻擊號令","Strategic Mind":"戰略心智","Overwhelming Attack":"壓倒性攻擊",
"Mantle of Courage":"勇氣斗篷","Incite Courage":"激發勇氣","Aura of Victory":"勝利靈光","Pillar of Confidence":"信心支柱",
"Mantle of Fear":"恐懼斗篷","Incite Fear":"激發恐懼","Unsettling Aura":"不安靈光","Incite Panic":"激發恐慌",
"Mantle of Fury":"狂怒斗篷","Incite Fury":"激發狂怒","Mindless Charge":"盲目衝鋒","Aura of Bloodletting":"放血靈光","Overwhelming Fury":"壓倒性狂怒",
"Mantle of Joy":"喜悅斗篷","Soothing Presence":"撫慰存在","Comforting Aura":"安慰靈光","Aura of Jubilation":"歡騰靈光","Beacon of Recovery":"復原信標",
"Mastery of Air":"氣之精通","Wind Step":"乘風步","Wind Stream":"氣流","Cloak of Air":"氣之斗篷","Wind Form":"風之形態","Misty Form":"霧之形態","Animate Air":"活化空氣",
"Mastery of Fire":"火之精通","Combustion":"燃燒","Rolling Flame":"翻滾烈焰","Detonation":"爆破","Fire Form":"火之形態","Animate Fire":"活化火焰",
"Mastery of Force":"力場精通","Push":"推","Move":"移動","Inertial Armor":"慣性護甲","Telekinetic Barrier":"心靈遙控屏障","Grasp":"抓握","Crush":"碾壓",
"Mastery of Ice":"冰之精通","Ice Spike":"冰刺","Ice Sheet":"冰面","Frozen Sanctuary":"冰封聖所","Frozen Rain":"冰雨","Ice Barrier":"冰之屏障",
"Mastery of Light and Darkness":"光暗精通","Darkness":"黑暗","Light":"光明","Shadow Beasts":"暗影野獸","Radiant Beam":"光耀光束",
"Mastery of Water":"水之精通","Desiccate":"脫水","Watery Grasp":"水之抓握","Water Whip":"水鞭","Water Breathing":"水中呼吸","Water Sphere":"水球","Animate Water":"活化水流",
"Mastery of Weather":"天候精通","Cloud Steps":"雲階","Hungry Lightning":"飢餓閃電","Wall of Clouds":"雲牆","Whirlwind":"旋風","Lightning Leap":"閃電躍","Wall of Thunder":"雷鳴之牆","Thunder Clap":"雷擊",
"Mastery of Wood and Earth":"木土精通","Animate Weapon":"活化武器","Warp Weapon":"扭曲武器","Warp Armor":"扭曲護甲","Wall of Wood":"木牆","Armored Form":"裝甲形態","Animate Earth":"活化大地",
"Mind Meld":"心靈融合","Mind Slam":"心靈重擊","Mind Thrust":"心靈刺擊","Mystic Charm":"秘術魅惑","Mystic Hand":"秘術之手",
"Nomadic Arrow":"遊牧之箭","Speed Dart":"疾速鏢","Seeking Missile":"追蹤飛彈","Faithful Archer":"忠實射手",
"Nomadic Chameleon":"遊牧變色龍","Chameleon":"變色龍","Step from Sight":"隱沒視線","Enduring Invisibility":"持久隱形",
"Nomadic Mind":"遊牧心智","Wandering Mind":"漫遊心智","Find Creature":"尋找生物","Item Lore":"物品知識","Psychic Speech":"心靈話語","Wandering Eye":"漫遊之眼","Phasing Eye":"相移之眼",
"Nomadic Step":"遊牧步","Step of a Dozen Paces":"十二步之躍","Nomadic Anchor":"遊牧錨點","Defensive Step":"防禦步","There and Back Again":"去而復返","Transposition":"位置互換","Baleful Transposition":"惡意互換","Phantom Caravan":"幻影商隊","Nomad's Gate":"遊牧者之門",
"Precognition":"預知","Precognitive Hunch":"預知直覺","All-Around Sight":"全方位視覺","Danger Sense":"危機感應","Victory Before Battle":"戰前必勝",
"Psionic Restoration":"靈能恢復","Mend Wounds":"癒合傷口","Restore Health":"恢復健康","Restore Life":"恢復生命","Restore Vigor":"恢復活力",
"Psionic Weapon":"靈能武器","Ethereal Weapon":"乙太武器","Lethal Strike":"致命打擊","Augmented Weapon":"強化武器",
"Psychic Assault":"心靈攻擊","Psionic Blast":"靈能衝擊","Ego Whip":"自我之鞭","Id Insinuation":"本我侵入","Psychic Blast":"心靈衝擊","Psychic Crush":"心靈粉碎",
"Psychic Disruption":"心靈干擾","Distracting Haze":"分心迷霧","Daze":"暈眩","Mind Storm":"心靈風暴","Psychic Hammer":"心靈之錘",
"Psychic Inquisition":"心靈審問","Hammer of Inquisition":"審問之錘","Forceful Query":"強力詢問","Ransack Mind":"搜刮心智",
"Phantom Idea":"幻影念頭","Psychic Phantoms":"心靈幻影","Distracting Figment":"分心虛像","Phantom Foe":"幻影敵人","Phantom Betrayal":"幻影背叛","Phantom Riches":"幻影財富",
"Telepathic Contact":"心靈感應接觸","Exacting Query":"精確詢問","Occluded Mind":"遮蔽心智","Broken Will":"破碎意志","Psychic Grip":"心靈掌控","Psychic Domination":"心靈支配",
"Third Eye":"第三隻眼","Tremorsense":"震顫感知","Unwavering Eye":"不動之眼","Piercing Sight":"穿透視覺","Truesight":"真實視覺",
};
