// 卡牌／牌組中「整句包在 {@i}／{@note} 裡」的句子（舊匯出規則會略過）→ i18n/exact-strings.json
import add from "../_addex.mjs";
const I = o => Object.fromEntries(Object.entries(o).map(([k, v]) => [`{@i ${k}}`, `{@i ${v}}`]));
const m = {
	"{@note See the appendices for printable assets.}": "{@note 可列印的素材見附錄。}",
	"{@note This deck item comprises the following individual cards:}": "{@note 這件牌組物品由下列各張卡牌組成：}",
	...I({
		// 更多萬象無常牌參考指南
		"A beholder hovers in a cluttered laboratory. The Aberration card embodies things contrary to nature.": "一隻眼魔懸浮在雜亂的實驗室中。異怪牌體現違反自然的事物。",
		"A set of scales holds day and night in balance. This card deals with many aspects of balance, or with things being out of balance.": "一座天秤讓白晝與黑夜保持平衡。這張牌涉及平衡的許多面向，或事物失去平衡的情況。",
		"The Beast card points to creatures of the animal kingdom and foul, cruel, or bad-tempered behavior in people.": "野獸牌指向動物界的生物，以及人們卑劣、殘酷或脾氣暴躁的行為。",
		"An enormous book rests among scrolls and parchment, with a quill and ink nearby. The Book card embodies written information.": "一本巨大的書擱在卷軸與羊皮紙之間，旁邊放著羽毛筆與墨水。書本牌體現書面資訊。",
		"A stone bridge arcs across a waterway. A shadowy figure lurks under the bridge, only its gleaming eyes clearly visible. This card reflects the effort required to overcome obstacles.": "一座石橋橫跨水道。一個陰暗的身影潛伏在橋下，只有那雙發亮的眼睛清晰可見。這張牌反映克服障礙所需的努力。",
		"A large campfire offers safety and comfort in the night. This card suggests a need for rest.": "一大堆營火在夜裡提供安全與慰藉。這張牌暗示需要休息。",
		"A vast cavern is adorned with glowing fungi and striking stone formations. The Cavern card suggests exploration and delving into hidden secrets.": "一座巨大的洞穴點綴著發光的真菌與引人注目的石造地貌。洞窟牌暗示探索與深入隱藏的祕密。",
		"A beautiful couatl twines through the clouds. This card suggests the involvement of celestial beings and service to the divine.": "一條美麗的羽蛇在雲間蜿蜒穿行。這張牌暗示天界存在的介入與對神聖的侍奉。",
		"A comet with an enormous tail streaks across the winter sky at night, outshining the stars. The Comet card brings dire warnings or devastation.": "一顆拖著巨大尾巴的彗星劃過冬夜的天空，光芒蓋過群星。彗星牌帶來可怕的警告或毀滅。",
		"A modron wields a wrench in the interior of a clockwork machine. This card signifies things made by hand, including Constructs.": "一個魔冢在發條機器的內部揮舞著扳手。這張牌象徵手工製作的事物，包括構裝體。",
		"An adventurer lies dead in a dungeon hallway, pierced by arrows. The Corpse card embodies decay and corruption.": "一名冒險者被箭矢射穿，死在地城的走廊上。屍體牌體現腐敗與墮落。",
		"A signpost points in many directions at a crossroads. The Crossroads cards warns of a difficult but necessary decision.": "十字路口的路標指向許多方向。十字路口牌警示一個困難但必要的決定。",
		"Underground stairs lead to a heavy door made of iron bars. This card represents both imprisonment and freedom.": "地下的階梯通往一扇以鐵條製成的沉重大門。這張牌同時代表囚禁與自由。",
		"A large wooden door bars the path ahead. The card offers an opportunity to change.": "一扇巨大的木門擋住了前方的路。這張牌提供改變的機會。",
		"A menacing red dragon perches atop its treasure hoard inside a cave. This card can point to things connected to Dragons, but it also suggests hoarding, reed, and places rich in magical energy.": "一頭兇惡的紅龍盤踞在洞穴中的寶藏堆上。這張牌可以指向與龍有關的事物，但也暗示囤積、貪婪，以及富含魔法能量的地方。",
		"A hungry Xorn feeds in an Underdark cavern. This card suggests an Elemental creature or reducing a thing to its essence.": "一隻飢餓的索爾石怪在幽暗地域的洞穴中進食。這張牌暗示元素生物，或將事物還原至其本質。",
		"A female medusa with a serpentine tail instead of legs is surrounded by flowers and herbs. The Euryale card points to vision, insight, and observation,": "一名以蛇尾取代雙腿的女性梅杜莎被花朵與藥草環繞。尤瑞艾莉牌指向視覺、洞察與觀察，",
		"A bard plays a musical instrument. This card implies expertise, rightly or wrongly applied.": "一位吟遊詩人演奏著樂器。這張牌意味著專業，無論運用得正確與否。",
		"Three sisters weave, measure, and cut the threads of fate. This card explores the repercussions of decisions and reflects on the past.": "三姊妹編織、丈量並剪斷命運之線。這張牌探討決定的後果並回顧過去。",
		"A blink dog runs through the wild. When upright; this card can refer to a Fey creature or a sense of whimsy; reversed, it points to the gloomy Shadowfell.": "一隻閃現犬在荒野中奔跑。正位時，這張牌可以指精類生物或異想天開的感覺；逆位時，它指向陰鬱的墮影冥界。",
		"A balor strikes from the depths of the Abyss. This card alludes to an actual Fiend or the forces of the Lower Planes.": "一隻巴洛炎魔從無底深淵的深處出擊。這張牌暗指真正的邪魔或下層位面的勢力。",
		"A chain devil, wreathed in flames, looks menacing and angry. The Flames card brings enemies and vengeance.": "一隻被火焰環繞的鏈魔看起來兇惡又憤怒。烈焰牌帶來敵人與復仇。",
		"A person walks down a path, unwittingly dropping items along the way. The Fool card represents innocence.": "一個人沿著小徑走，沿途不知不覺掉落物品。愚者牌代表純真。",
		"A large, faceted gemstone set in intricate filigree gleams invitingly. The Gem card brings vast wealth.": "一顆鑲在精緻金銀絲工藝中的大顆刻面寶石閃耀著誘人的光芒。寶石牌帶來巨大的財富。",
		"A hungry troll lurks in a forest clearing. The Giant card indicates something very large or that looms large in one's perception.": "一隻飢餓的巨魔潛伏在林間空地。巨人牌表示某個非常巨大的東西，或在某人認知中顯得巨大的東西。",
		"Kobolds set a trap in their cave lair. This card points to the importance of empathy in relationships with other people.": "狗頭人在牠們的洞穴巢穴中設置陷阱。這張牌指出同理心在人際關係中的重要性。",
		"A person wearing jester's motley and holding a staff rests his foot on a skull. This card deals with the relationship between humor and misfortune.": "一個身穿弄臣彩衣、手持權杖的人把腳踩在一顆頭骨上。這張牌涉及幽默與不幸之間的關係。",
		"This large metal key is bizarrely complicated. The Key card represents the perfect solution to a problem or having the right tool for the job.": "這把巨大的金屬鑰匙複雜得離奇。鑰匙牌代表問題的完美解答，或擁有適合這份工作的工具。",
		"A knight formed of folded cards offers a sword also made from cards. The Knight card signifies trust and loyalty.": "一名由摺疊卡牌構成的騎士獻上一把同樣以卡牌製成的劍。騎士牌象徵信任與忠誠。",
		"An ornate dragonlance shines among more ordinary weapons on a rack. The Lance card warns that healing sometimes requires additional injury, as when infection must be cut away.": "一把華麗的屠龍槍在武器架上較普通的武器之間閃耀。騎槍牌警示治癒有時需要額外的傷害，就像必須切除感染之處一樣。",
		"A warlock holds a black crystalline staff. This card suggests both mental acuity and arcane magic.": "一名契術師握著一根黑色水晶法杖。這張牌同時暗示敏銳的心智與奧術魔法。",
		"X marks the spot on an elaborate treasure map. The Map card provides guidance that leads to the goal of the quest.": "一張精細的藏寶圖上以 X 標出了地點。地圖牌提供通往任務目標的指引。",
		"Unfortunate souls are trapped in an elaborate and impossible maze of cards. Those who draw the Maze card are lost.": "不幸的靈魂被困在一座由卡牌構成、精巧而不可能存在的迷宮中。抽到迷宮牌的人迷失了方向。",
		"A well-crafted pick leans against a wall at the entrance to a mine. The Mine card represents something valuable underground or buried in the earth.": "一把作工精良的鎬靠在礦坑入口的牆上。礦坑牌代表地下或埋在土中的貴重之物。",
		"An owlbear sits in a sunny glade. This card represents something monstrous, including familiar things that turn strange and threatening.": "一隻梟熊坐在陽光明媚的林間空地上。這張牌代表怪物般的事物，包括變得陌生而具威脅性的熟悉事物。",
		"A crescent moon looms large in the autumn sky. The Moon card points to hidden potential.": "一彎新月高掛在秋日的天空。月亮牌指向隱藏的潛能。",
		"A gelatinous cube with various items suspended inside it creeps through a vaulted sewer. The Ooze card indicates the importance of something that seems lowly or innocuous.": "一隻體內懸浮著各種物品的凝膠方塊在拱頂下水道中蠕行。泥怪牌表示某個看似卑微或無害之物的重要性。",
		"A well-worn path twists through the wilderness, with hidden dangers lurking in the shadows to both sides. This card suggests the importance of sticking with a plan and remaining focused on the destination.": "一條久經踩踏的小徑蜿蜒穿過荒野，兩側的陰影中潛伏著隱藏的危險。這張牌暗示堅持計畫並專注於目的地的重要性。",
		"A deep hole studded with spikes gapes in the earth. The Pit card represents a literal or metaphorical fall—losing status, wealth, or position.": "一個佈滿尖刺的深坑在地上張著大口。坑洞牌代表字面上或比喻上的墜落——失去地位、財富或職位。",
		"A myconid emits a cloud of spores. The Plant card reflects growth and natural life.": "一隻蕈人噴出一團孢子雲。植物牌反映生長與自然的生命。",
		"A cleric holds a heavy mace. The Priest card represents wisdom, insight, closeness to the divine, and divine magic.": "一名牧師握著沉重的硬頭錘。祭司牌代表智慧、洞察、與神聖的親近，以及神聖魔法。",
		"A rogue begs for release from a dank prison cell. The Prisoner card represents someone or something locked and hidden away.": "一名游蕩者在陰濕的牢房中乞求獲釋。囚犯牌代表被鎖起來並藏匿的某人或某物。",
		"An elaborate puzzle box floats in the air, glowing from within. The Puzzle card speaks to intelligence and strategic thinking.": "一個精巧的機關盒漂浮在空中，從內部發出光芒。謎題牌訴說著智力與策略思考。",
		"An emerald ring glows within a decorative jewelry box. The Ring card suggests both a promise and the honor involved in keeping it.": "一枚綠寶石戒指在裝飾華美的珠寶盒中發光。戒指牌同時暗示承諾與信守承諾所涉及的榮譽。",
		"A roguish kenku lurking in the shadows holds a dagger, poised to strike. This card suggests treachery and deception.": "一名潛伏在陰影中的無賴天狗握著匕首，蓄勢待發。這張牌暗示背叛與欺騙。",
		"An elegant sword and crown disintegrate into eddies of ash. The Ruin card warns of the inevitability of decay and the danger of material attachments.": "一把優雅的劍與一頂王冠崩解成盤旋的灰燼。毀滅牌警示衰敗的必然與依戀物質的危險。",
		"The mind of a sage is filled with obscure lore gained through exhaustive research. This card represents well-intentioned advice.": "賢者的腦中裝滿了透過詳盡研究得來的冷僻知識。這張牌代表出於善意的建議。",
		"A circular shield is close at hand in a military barrack. The Shield card is a reminder of the need for protection.": "軍營中，一面圓盾就放在手邊。盾牌牌提醒人們需要保護。",
		"A three-masted ship with a couatl figurehead sails across the open sea. The Ship card indicates a long journey, not necessarily by sea.": "一艘以羽蛇為船首像的三桅船航行在開闊的海面上。船牌表示一段漫長的旅程，不一定是海路。",
		"A skeletal figure is shrouded in a swirling robe, though its skull is clearly visible. The Skull card is a reminder of the universality of death—and the fact that everyone must confront death alone.s": "一個骷髏般的身影裹在翻飛的長袍中，但其頭骨清晰可見。骷髏牌提醒人們死亡的普遍性——以及每個人都必須獨自面對死亡的事實。",
		"An elegant black staff leans against a wall, waiting for its owner to return. The Staff card represents support or assistance.": "一根優雅的黑色法杖靠在牆上，等待主人歸來。法杖牌代表支持或協助。",
		"A spiral stairway leads both up and down, but the downward stairs are cluttered and dark. This card points to a change in difficulty, either increasing or decreasing.": "一座螺旋樓梯同時通往上方與下方，但向下的階梯雜亂又昏暗。這張牌指向難度的變化，可能增加也可能減少。",
		"A brilliant star shines in the spring sky at twilight. The Star card represents inherent ability and training working in concert—nature allied with nurture.": "一顆明亮的星在春日黃昏的天空中閃耀。星辰牌代表天生的能力與訓練相輔相成——先天與後天的結合。",
		"A sun blazes brightly in the summer sky. The Sun card brings hope—either well-founded or deluded.": "太陽在夏日的天空中熾烈燃燒。太陽牌帶來希望——無論是有憑有據還是自欺欺人。",
		"A clawed hand reaches to grab an emerald ring which disintegrates at the claw's approach. The Talons card indicates greed or the rapacious hunger of a predator.": "一隻長著利爪的手伸向一枚綠寶石戒指，戒指在爪子接近時崩解。利爪牌表示貪婪，或掠食者貪得無厭的飢渴。",
		"An adventuring party eats and laughs in a busy tavern. The Tavern card points to the pleasure of spending time with friends.": "一支冒險隊伍在熱鬧的酒館裡吃喝談笑。酒館牌指向與朋友共度時光的樂趣。",
		"A temple invites worshipers into the serene space within. The Temple card suggests the comfort found in ritual and communion with the divine.": "一座神殿邀請信徒進入其寧靜的內部空間。神殿牌暗示在儀式與和神聖的交流中找到的慰藉。",
		"An ostentatious throne stands on a dais, with a crown on the seat and a ceremonial sword leaning against one armrest. This card represents the authority of worldly rulers.": "一張浮華的王座立在高台上，座位上放著一頂王冠，一把儀式用劍靠在一側扶手上。這張牌代表世俗統治者的權威。",
		"A burial chamber holds a plain stone casket. The Tomb card suggests buried secrets and things long forgotten.": "一間墓室中放著一口樸素的石棺。墳墓牌暗示被埋藏的祕密與早已被遺忘的事物。",
		"A tall, ornate tower made of black stone looms over a desolate landscape. The Tower card represents isolation.": "一座以黑石建成的高聳華麗之塔聳立在荒涼的大地上。高塔牌代表孤立。",
		"A tree has broken through a fortress wall and reclaimed part of the keep. This card suggests perseverance in difficult circumstances.": "一棵樹衝破了要塞的牆，重新占據了部分主堡。這張牌暗示在艱困環境中的堅持。",
		"A lich beckons souls of the dead. This card can point to anything that refuses to die, from old grudges and unresolved issues to Undead creatures.": "一名巫妖召喚著死者的靈魂。這張牌可以指向任何拒絕死去的事物，從舊怨與懸而未決的問題到不死生物。",
		"An endless void seems to spiral toward a central hole that devours all. This card spells disaster.": "無盡的虛空彷彿盤旋著流向中央那吞噬一切的洞。這張牌預示災難。",
		"A barbarian holds a greataxe, The Warrior card embodies physical strength and fighting acumen.": "一名野蠻人握著巨斧，戰士牌體現體能與戰鬥才幹。",
		"A stone well stands in a peaceful meadow, surrounded by wildflowers. The Well card speaks of drawing resources from familiar places.": "一口石井立在寧靜的草地上，周圍開滿野花。水井牌訴說著從熟悉之處汲取資源。",
		// 長老符文
		"Elder Rune of Protection and Sacrifice": "守護與犧牲的長老符文", "Elder Rune of War": "戰爭的長老符文", "Elder Rune of the Mad Mage": "瘋法師的長老符文", "Elder Rune of Chaos": "混亂的長老符文", "Elder Rune of Fire": "火焰的長老符文",
		"Elder Rune of Security": "安全的長老符文", "Elder Rune of Decision": "抉擇的長老符文", "Elder Rune of Goblinkind": "類哥布林的長老符文", "Elder Rune of Passage": "通行的長老符文",
		// 夥伴卡
		"Human Spellcaster": "人類施法者", "Human Expert": "人類專家", "Moon Elf Warrior": "月精靈戰士", "Lightfoot Halfling Spellcaster": "輕足半身人施法者", "Lightfoot Halfling Warrior": "輕足半身人戰士", "Shield Dwarf Warrior": "盾矮人戰士",
		// 歐姆的詭術神
		"(pronounced EYE-jin)": "（讀作 EYE-jin）", "(pronounced KOO-bah-zahn)": "（讀作 KOO-bah-zahn）", "(pronounced MOH-ah)": "（讀作 MOH-ah）", "(pronounced NANG-nang)": "（讀作 NANG-nang）", "(pronounced oh-boh-LAH-kah)": "（讀作 oh-boh-LAH-kah）",
		"(pronounced pah-pah-ZAH-tul)": "（讀作 pah-pah-ZAH-tul）", "(pronounced shah-GOM-bee)": "（讀作 shah-GOM-bee）", "(pronounced UNK)": "（讀作 UNK）", "(pronounced WONG-go)": "（讀作 WONG-go）",
		// 塔羅牌組的冒險引子
		"A mysterious order of assassins begins to hunt down a member of the party.": "一個神祕的刺客組織開始追殺隊伍中的一名成員。",
		"The party meets a powerful Wizard whom they may ask one question and get a truthful answer from.": "隊伍遇見一位強大的法師，可以向他問一個問題並得到真實的回答。",
		"A nobleman's children have run away to join the Lord Montague's Monstrous Circus. He begs that you find and return them.": "一位貴族的孩子離家出走，加入了蒙塔古勳爵的怪物馬戲團。他懇求你們找到並帶回他們。",
		"A group of elves asks if the party would aid them in recovering a sacred artifact.": "一群精靈詢問隊伍是否願意協助他們尋回一件神聖的神器。",
		"A vampire Lord offers you the gift of eternal undeath in exchange for a single favor.": "一位吸血鬼領主願意賜予你永恆的不死，以換取你幫一個忙。",
		"A dwarven forgemaster has had her magical hammer stolen and is asking for your help. In return, she'll forge you a weapon.": "一位矮人鍛造大師的魔法錘被偷了，正請求你的協助。作為回報，她會為你鍛造一件武器。",
		"A nearby village has been invaded by the drow and seeks aid.": "附近的一座村莊遭到卓爾入侵，正在尋求援助。",
		"During a lightning storm, the adventurers see an entrance to a cavern. It is home to a coven of hags.": "在一場雷暴中，冒險者看見一個洞穴的入口。那是一個鬼婆集會的家。",
		"Graves of a cemetery appear to be robbed, but some say it was the dead that dug their way out.": "墓園的墳墓看似遭到盜掘，但有人說是死者自己挖出來的。",
		"A kobold asks if the party wishes to join him on an adventure to the Dragon's Teeth mountains to find the fabled Eye of Tiamat.": "一隻狗頭人詢問隊伍是否願意與他一同前往龍牙山脈冒險，尋找傳說中的提雅瑪特之眼。",
		"The adventurers encounter two nobles fighting over a magical (but cursed) item.": "冒險者遇到兩名貴族為了一件魔法（但受詛咒的）物品而爭鬥。",
		"A traveling circus's giant spider has died, leaving its owner distraught. Can you get some giant spider eggs for him to hatch?": "巡迴馬戲團的巨蜘蛛死了，牠的主人傷心欲絕。你能幫他弄些巨蜘蛛卵來孵化嗎？",
		"A revenant tells you its story and asks for aid in completing its act of vengeance.": "一名還魂屍向你訴說它的故事，並請求協助完成它的復仇。",
		"A dwarf claims to have discovered a vein of mithral in his mine, but now monsters have moved in, and he needs help reclaiming it.": "一名矮人聲稱在他的礦坑中發現了一條秘銀礦脈，但現在怪物搬了進來，他需要幫忙把它奪回來。",
		"The next short rest you take acts as a long rest instead.": "你進行的下一次短休改為視同長休。",
		"The mayor of a small town has declared tieflings a \"threat to moral decency\" and wants them rounded up and detained.": "一座小鎮的鎮長宣稱提夫林是「對道德風俗的威脅」，並想把他們全部圍捕拘留。",
		"You discover a treasure map within an ornate box in the hollow of an old tree.": "你在一棵老樹樹洞裡的華麗盒子中發現一張藏寶圖。",
		"A hill giant is sleeping off a night of drinking. Inside a chain mail pouch on its belt, you can hear someone whispering for help.": "一名山丘巨人喝了一夜的酒後正在呼呼大睡。你能聽見他腰帶上的鎖子甲袋裡有人低聲求救。",
		"A poor villager comes to you seeking aid and offers you a rare magic item in compensation.": "一名貧窮的村民前來向你求助，並願意以一件稀有魔法物品作為報酬。",
		"Is there a bard in the party? The king is having a ball and the entertainment has not shown up.": "隊伍裡有吟遊詩人嗎？國王正在舉辦舞會，而表演者還沒出現。",
		"A queen has fallen under a witch's curse. You have been asked to help break the spell.": "一位女王中了女巫的詛咒。有人請你協助破除這道咒語。",
		"While traveling, the party comes across a nest of yuan-ti that are planning on enslaving a nearby village.": "旅途中，隊伍遇到一窩正計畫奴役附近村莊的蛇人。",
		"A noble approaches you and says that an assassin has been sent to kill him and he needs your help.": "一名貴族找上你，說有人派了刺客來殺他，他需要你的幫助。",
		"The local mad wizard wants basilisk or cockatrice eggs and is willing to pay handsomely.": "當地的瘋法師想要石化蜥蜴或雞蛇獸的蛋，並願意重金收購。",
		"A holy order needs your aid to sanctify a place defiled by demons.": "一個神聖修會需要你的協助，淨化一處被惡魔玷汙的地方。",
		"The adventurers find a sending stone. On the other end is someone who is in deep trouble and is pleading for help.": "冒險者找到一顆傳訊石。另一端是某個深陷麻煩、正在懇求幫助的人。",
		"There were whispers that the mayor of the town was seen signing a pact with an imp.": "有傳言說，有人看見鎮長與一隻小魔鬼簽下契約。",
		"Something is digging tunnels under the city and your party has been asked to investigate.": "有東西正在城市底下挖掘隧道，有人請你的隊伍前去調查。",
		"A mind flayer has used an intellect devourer to take over the prison warden. It uses him to prey on the prisoners.": "一隻奪心魔用噬腦怪控制了典獄長，並利用他來獵食囚犯。",
		"Evil from a haunted house has begun to blight the village farms in the valley below. Farmers have taken a collection to pay you to clear out the evil.": "來自鬼屋的邪惡開始使下方山谷中的村莊農田枯萎。農民們湊了一筆錢，要付給你們去清除那股邪惡。",
		"A horde of marauders is rumoured to be en route to a village. The townsfolk ask the party for help.": "傳聞有一大群掠奪者正朝一座村莊而來。鎮民向隊伍求助。",
		"Something has torn down the rope bridge that spans the chasm. The villagers need help rebuilding it.": "有東西扯斷了橫跨裂谷的繩橋。村民需要幫忙重建它。",
		"A wizard wants you to find her some rare spell components.": "一位法師想請你幫她找一些稀有的法術構材。",
		"A \"holy\" order of priests (actually evil) want you to retrieve a sacred object stolen from them. It's a unicorn's horn that was stolen by a real holy person.": "一個「神聖」的祭司修會（其實是邪惡的）想請你取回一件從他們那裡被偷走的聖物。那是一支獨角獸的角，是被一位真正的聖者偷走的。",
		"A man staggers toward you and hands you a silver key. He gasps, \"find the fish,\" before falling over dead. He smells of brine.": "一名男子踉蹌地走向你，把一把銀鑰匙交給你。他喘著氣說：「找到那條魚」，然後倒地身亡。他身上有海水的鹹味。",
		"A farmer claims that his goose that lays golden eggs has been stolen by a cyclops and is asking for your help in getting it back.": "一名農夫聲稱他那隻會下金蛋的鵝被獨眼巨人偷走了，正請你幫忙把牠找回來。",
		"Someone comes to you with a murder mystery that they want you to solve.": "有人帶著一樁謀殺懸案來找你，希望你能破案。",
		"The party is asked to escort a political figure across a hostile terrain.": "有人請隊伍護送一位政治人物穿越一片充滿敵意的地帶。",
		"A duck waddles up and says that he has witnessed a murder and wants you to catch the culprit.": "一隻鴨子搖搖擺擺地走過來，說牠目擊了一樁謀殺案，希望你抓住兇手。",
		"The town mayor is rumoured to be possessed by an evil spirit. The mayor is secretly preparing to sacrifice the entire town.": "傳聞鎮長被邪靈附身了。鎮長正暗中準備獻祭整座城鎮。",
		"A doppelgänger has infiltrated the king's court and the king seeks someone who can root him out.": "一名二重身滲透了國王的宮廷，國王正在尋找能把他揪出來的人。",
		"A librarian has discovered a hidden stone door covered with magical glyphs in the library's basement.": "一名圖書館員在圖書館的地下室發現了一扇佈滿魔法符印的隱藏石門。",
		"An old Mariner tells you the precise location of a legendary shipwreck off the coast.": "一位老水手告訴你外海一艘傳奇沉船的確切位置。",
		"A ghost approaches a member of the party claiming to be a long-dead relative. It seeks vengeance.": "一個幽魂接近隊伍中的一名成員，自稱是其早已過世的親戚。它尋求復仇。",
		"The party is asked to have a young person accompany the group on their next adventure as a coming-of-age ceremony.": "有人請隊伍讓一名年輕人在下一次冒險中同行，作為成年禮。",
		"You find a gem. When you turn toward a distant mountain, the gem pulsates and glows.": "你找到一顆寶石。當你轉向遠方的一座山時，寶石會脈動並發光。",
		"A burly warrior bars the way and challenges anyone to hand-to-hand combat.": "一名魁梧的戰士擋住去路，向任何人發出徒手搏鬥的挑戰。",
		"A Paladin requests aid to recover the body of his fallen companion.": "一名聖騎士請求協助，尋回他陣亡同伴的遺體。",
		"The mayor of the town is missing. She has been charmed by a vampire.": "鎮長失蹤了。她被一名吸血鬼魅惑了。",
		"A benevolent order of druids wants their sacred stone back. It's in the crown of a pompous but powerful king.": "一個仁慈的德魯伊修會想取回他們的聖石。它就在一位自大卻強大的國王的王冠上。",
		"The party comes across a magical portal with a ring of standing stones.": "隊伍遇到一座被一圈立石環繞的魔法傳送門。",
		"You find a trapped efreet who offers you his services for a year if you can find a way to free him.": "你發現一名受困的火巨靈，若你能設法釋放他，他願意為你效勞一年。",
		"You encounter a devil who offers you a rare magic item in exchange for a favor.": "你遇到一名魔鬼，他願意以一件稀有魔法物品換取你幫一個忙。",
		"You encounter a king of a far-off land who seeks your aid.": "你遇到一位來自遙遠國度的國王，他尋求你的援助。",
		"You encounter the queen of a nation with an important mission for you.": "你遇到一國的女王，她有一項重要的任務要交給你。",
		"You encounter a gnome who says that if you follow him, he'll lead you to a wondrous treasure.": "你遇到一名地侏，他說只要你跟著他，他就會帶你找到一件奇妙的寶藏。",
		"You have a strange dream of talking about life with an otyugh. When you wake up, you gain one permanent point of Wisdom.": "你做了一個奇怪的夢，夢見與一隻食腐獸暢談人生。醒來時，你的感知永久提升 1 點。",
		"You meet a monk who is looking for worthy adventurers to defeat a magical monster.": "你遇見一位武僧，他正在尋找夠格的冒險者去擊敗一隻魔法怪物。",
		"You find a holy book written by a wise sage that contains a cryptic secret hidden within it.": "你找到一本由睿智賢者所寫的聖典，其中藏著一個隱晦的祕密。",
		"You encounter a holy woman who offers you each a gift.": "你們遇到一位聖女，她送給你們每人一份禮物。",
		"A mysterious person presents you with a tempting offer.": "一個神祕人向你提出一個誘人的提議。",
		"You meet a sage who gives you a key that opens a magical lock.": "你遇見一位賢者，他給了你一把能打開魔法鎖的鑰匙。",
		"You encounter a sorcerer who wants you to look into her crystal ball.": "你遇到一位術士，她想請你看看她的水晶球。",
		"You find a mechanical toy puppet that always walks to the nearest tavern.": "你找到一個機械玩具人偶，它總是會走向最近的酒館。",
		"The Earth around you mysteriously begins to shake in a violent earthquake.": "你周圍的大地神祕地開始劇烈搖晃，發生了強烈的地震。",
		"You meet a halfling wizard who—If you treat him kindly—gives you a \"wink of good luck.\" You gain advantage on your next role.": "你遇見一位半身人法師，若你善待他，他會給你一個「好運的眨眼」。你的下一次擲骰具有優勢。",
		"You see someone weeping at the side of the road. They are being forced to marry someone they don't want to.": "你看見有人在路邊哭泣。他們正被迫與自己不想嫁娶的人結婚。",
		"A shy ogre asks the party to rescue his pet goat from an evil cyclops.": "一隻害羞的食人魔請隊伍從邪惡的獨眼巨人手中救出他的寵物山羊。",
		"A weeping dryad asks you to save her forest from destruction at the hands of orcs.": "一名哭泣的樹精請你拯救她的森林，免於毀在獸人手中。",
		"A young paladin-in-training says that his order has stolen an object sacred to hobgoblins. He feels guilty and wants to steal it and give it back to them.": "一名年輕的見習聖騎士說，他的修會偷走了一件對大哥布林而言神聖的物品。他感到內疚，想把它偷出來還給他們。",
		"You were invited by the mayor of a nearby town to take part in their \"Festival of Monsters\".": "附近一座城鎮的鎮長邀請你們參加他們的「怪物節」。",
		"A group of Viking Warriors are in a longboat. They claim to found a way to the river Styx, and they're going to fight devils.": "一群維京戰士坐在一艘長船上。他們聲稱找到了通往冥河的路，並打算去和魔鬼戰鬥。",
		"You see a lever that is inscribed with magical symbols. Do you pull it?": "你看見一根刻有魔法符號的拉桿。你要拉它嗎？",
		"A drunken beggar in an alley swears to you he saw the king's son turn into a werewolf. There have been grisly killings in the city.": "巷子裡一名喝醉的乞丐向你發誓，他看見國王的兒子變成了狼人。城裡發生了多起駭人的命案。",
		"You are approached by the captain of the city guard to see if you will track down and capture a dangerous criminal.": "城市衛隊的隊長找上你，想知道你是否願意追查並逮捕一名危險的罪犯。",
	}),
};
// TCE 夥伴職業特性：{@i 8th-level Warrior feature}
const CL = {Warrior: "戰士", Expert: "專家", Spellcaster: "施法者"};
for (let lv = 1; lv <= 20; lv++) for (const [en, zh] of Object.entries(CL)) {
	const ord = lv + (lv % 10 === 1 && lv !== 11 ? "st" : lv % 10 === 2 && lv !== 12 ? "nd" : lv % 10 === 3 && lv !== 13 ? "rd" : "th");
	m[`{@i ${ord}-level ${en} feature}`] = `{@i ${lv} 級${zh}特性}`;
}
add(m);
