import F from "./_fillidx.mjs";
const W = {
 "Character Traits": "角色特徵",
 "As the players choose backgrounds for their characters, they can use the following tables to help determine their characters' personality traits, ideals, bonds, and flaws. Players can use these tables instead of the ones that appear in the {@book Player's Handbook|PHB}, or they can mix and match them. If a rolled result doesn't make sense for a character, the player can roll again or choose a more appropriate entry on the table.": "玩家為角色選擇背景時，可以使用下列表格來協助決定角色的個性特徵、理想、牽絆與缺點。玩家可以用這些表格取代{@book Player's Handbook|PHB}中的表格，也可以混合搭配。若擲出的結果對角色而言不合理，玩家可以重擲，或從表中選擇更合適的條目。",
 "These tables, while optional, are well suited to Feywild-themed adventures and are ideal for any character who has the feylost or Witchlight hand background.": "這些表格雖然是選用的，但很適合以妖精荒野為主題的冒險，也非常適合擁有妖精迷途者或魔光工作人員背景的任何角色。",
 "Trait": "特徵",
 "I'm haunted by fey laughter that only I can hear, though I know it's just my mind playing tricks on me.": "我被只有我聽得見的妖精笑聲糾纏，雖然我知道那只是我的腦袋在捉弄我。",
 "Like a nomad, I can't settle down in one place for very long.": "我像遊牧民族一樣，無法在一個地方久待。",
 "Good music makes me weep like a baby.": "好聽的音樂會讓我哭得像個嬰兒。",
 "Wherever I go, I try to bring a little of the warmth and tranquility of home with me.": "無論走到哪裡，我都試著帶著一點家的溫暖與寧靜。",
 "I have never lost my childlike sense of wonder.": "我從未失去孩子般的好奇心。",
 "When I have a new idea, I get wildly excited about it until I come up with another, better idea.": "當我有了新點子，我會興奮得不得了，直到我想出另一個更好的點子為止。",
 "I live by my own set of weird and wonderful rules.": "我依照自己一套古怪又奇妙的規則過活。",
 "I can't bring myself to trust most adults.": "我沒辦法信任大多數大人。",
 "Friendship. I never leave a friend behind. (Good)": "友誼。我絕不丟下朋友。（善良）",
 "Empathy. No creature should be made to suffer. (Good)": "同理。任何生物都不該受苦。（善良）",
 "Wanderlust. I prefer to take the less traveled path. (Chaotic)": "流浪癖。我比較喜歡走人跡罕至的路。（混亂）",
 "Changeability. Change is good, which is why I live by an ever-changing set of rules. (Chaotic)": "多變。改變是好事，所以我依照一套不斷變化的規則過活。（混亂）",
 "Honor. A deal is a deal, and I would never break one. (Lawful)": "榮譽。說好的事就是說好的事，我絕不違約。（守序）",
 "Rule of Three. Everything in the multiverse happens in threes. I see the \"rule of three\" everywhere. (Lawful)": "三之法則。多元宇宙中的一切都以三為單位發生。我到處都看得到「三之法則」。（守序）",
 "Obsession. I won't let go of a grudge. (Evil)": "執念。我不會放下怨恨。（邪惡）",
 "Greed. I will do whatever it takes to get what I want, regardless of the harm it might cause. (Evil)": "貪婪。為了得到我想要的東西，我會不擇手段，不管可能造成什麼傷害。（邪惡）",
 "I would never break my word.": "我絕不食言。",
 "I find magic in all its forms to be compelling. The more magical a place, the more I am drawn to it.": "我覺得各種形式的魔法都令人著迷。一個地方越有魔力，就越吸引我。",
 "I do what I can to protect the natural world.": "我盡我所能保護自然界。",
 "A trusted friend is the most important thing in the multiverse to me.": "對我來說，值得信賴的朋友是多元宇宙中最重要的東西。",
 "I can't bring myself to harm a Fey creature, either because I consider myself one or because I fear the repercussions.": "我狠不下心傷害妖精生物，可能是因為我認為自己也是其中之一，或是因為我害怕後果。",
 "The Witchlight Carnival feels like home to me.": "魔光嘉年華對我來說就像家一樣。",
 "I'm drawn to the Feywild and long to return there, if only for a short while.": "我受妖精荒野吸引，渴望回到那裡，哪怕只是短暫停留。",
 "I feel indebted to {@creature Mister Witch|WBtW} and {@creature Mister Light|WBtW} for giving me a home and a purpose.": "我覺得虧欠{@creature Mister Witch|WBtW}與{@creature Mister Light|WBtW}，因為他們給了我一個家與人生目標。",
 "I easily lose track of time. My poor sense of time means I'm always late.": "我很容易忘記時間。我的時間觀念很差，所以總是遲到。",
 "I think the whole multiverse is out to get me.": "我覺得整個多元宇宙都想害我。",
 "I'm always operating under a tight timeline, and I'm obsessed with keeping everything on schedule.": "我總是在緊迫的時間表下行動，執著於讓一切都按照進度進行。",
 "I'm a kleptomaniac who covets shiny, sparkling treasure.": "我有偷竊癖，覬覦閃閃發亮的寶物。",
 "I'm forgetful. Sometimes I can't remember even the simplest things.": "我很健忘。有時連最簡單的事都記不起來。",
 "I never give away anything for free and always expect something in return.": "我從不白白送出任何東西，總是期待得到回報。",
 "I have many vices and tend to indulge them.": "我有很多惡習，而且往往放縱它們。",
 "I'm always changing my mind—well, almost always.": "我總是在改變主意——嗯，幾乎總是。",
};
F("bg-WBtW", [
{0: "妖精迷途者", 2: "{@skill Deception}、{@skill Survival}", 4: "一種{@filter 樂器|items|source=phb|miscellaneous=mundane|type=instrument}", 6: "從{@language Elvish}、{@language Gnomish}、{@language Goblin}或{@language Sylvan}中選擇一種",
 8: "一件{@filter 樂器|items|source=phb|miscellaneous=mundane|type=instrument}（自選一種）、一套{@item Traveler's Clothes|PHB|旅行服裝}、三件小飾品（各在{@item Feywild Trinket|WBtW|妖精荒野小飾品}表上擲骰決定），以及一個裝有 8 gp 的{@item pouch|phb}",
 9: "特性：妖精荒野連結", 10: "你的舉止與對妖精習俗的了解會被妖精荒野的原住民認出，他們會把你視為自己人。因此，若你在妖精荒野中迷路或需要幫助，友善的妖精生物會傾向伸出援手。",
 11: "妖精印記", 12: "你在妖精荒野的停留讓你產生了些微的轉變，並獲得了一個妖精印記，在「妖精印記」表上擲骰決定。", 13: "妖精印記", 15: "妖精印記",
 16: "你的眼睛流轉著虹彩般的色彩。", 17: "你身上有一股甜甜的香味，像花蜜或蜂蜜。", 18: "你有像貓一樣的長鬍鬚。", 19: "你的耳朵覆蓋著柔軟的毛簇。", 20: "你的皮膚在月光下閃閃發光。", 21: "花朵在你面前會綻放或凋謝（由你選擇）。", 22: "你的頭髮由藤蔓或荊棘構成，剪斷後 1 小時內就會長回原本的長度。", 23: "你有一條像狗或其他動物的尾巴。",
 24: "妖精荒野訪客", 25: "每當你在長休期間熟睡或深度出神時，若 DM 希望，一個妖精荒野的精魂可能會來拜訪你。在「妖精荒野訪客」表上擲骰決定精魂的形態。這種拜訪絕不會對你造成傷害，可能持續數分鐘或數小時，而你醒來時會記得每一次拜訪。與訪客的對話內容可以是任何事，從訊息與洞見到胡言亂語與誤導線索，由 DM 決定。這類對話總是以你能理解的語言進行，即使妖精荒野訪客通常不會說那種語言。",
 26: "妖精荒野訪客", 28: "訪客", 29: "覺醒生物（被施展了{@spell awaken}法術的野獸或普通植物）"},
{0: "魔光工作人員", 2: "{@skill Performance}、{@skill Sleight of Hand}", 4: "{@item Disguise kit|phb}或一種{@filter 樂器|items|source=phb|miscellaneous=mundane|type=instrument}",
 8: "一個{@item disguise kit|PHB}或一件自選的{@filter 樂器|items|source=phb|miscellaneous=mundane|type=instrument}、一副紙牌、一套嘉年華制服或{@item costume clothes|phb|戲服}、一件小飾品（在{@item Feywild Trinket|WBtW|妖精荒野小飾品}表上擲骰決定），以及一個裝有 8 gp 的{@item pouch|phb}",
 9: "特性：嘉年華常駐成員", 10: "魔光嘉年華為你提供免費的簡樸住宿與食物。此外，只要你不干擾表演或惹出其他麻煩，你可以在嘉年華中四處閒逛，免費享受它的眾多奇景。",
 11: "嘉年華夥伴", 12: "多年來，你贏得了另一位嘉年華常駐成員的友誼。擲一顆 {@dice d8} 並查閱「嘉年華夥伴」表，決定你與誰或什麼成為朋友，或者你也可以選擇你喜歡的選項。與你的 DM 合作充實這段友誼。你在嘉年華中時，這位夥伴會在你身邊出沒，但它不會自願離開嘉年華。",
 13: "DM 可以使用{@adventure 第 1 章|WBtW|1}中的{@creature Witchlight Hand (Medium)|WBtW|魔光工作人員}數據區塊，代表作為嘉年華夥伴的工作人員、表演者與馴獸師。其他夥伴的數據見{@book Monster Manual|MM}。",
 14: "嘉年華夥伴", 16: "夥伴", 17: "年老、脾氣暴躁的魔光工作人員", 18: "年輕、容易受影響的魔光工作人員", 19: "表演者（例如特技演員、小丑或樂手）", 20: "退休的表演者", 21: "經驗豐富的馴獸師", 22: "年老的{@creature blink dog}", 23: "開朗的{@creature sprite}", 24: "無害的魔法光點（不需要數據區塊），擁有 30 呎的飛行速度，可以懸浮，並在 5 呎半徑內發出明亮光照，在其外額外 5 呎發出微光"},
], W);
const HR = {
 "Horror Characteristics": "恐怖特徵",
 "Characters in a horror-focused campaign might have distinct motivations and characteristics. Use the following tables to supplement your background's suggested characteristics or to inspire those of your own design.": "以恐怖為主題的戰役中，角色可能有獨特的動機與特徵。使用下列表格來補充你背景的建議特徵，或激發你自己設計特徵的靈感。",
 "Horror Character Personality Traits": "恐怖角色個性特徵", "Horror Character Ideals": "恐怖角色理想", "Horror Character Bonds": "恐怖角色牽絆", "Horror Character Flaws": "恐怖角色缺點",
 "I had an encounter that I believe gives me a special affinity with a supernatural creature or event.": "我曾有過一次遭遇，我相信那讓我與某個超自然生物或事件有了特殊的親近感。",
 "A signature piece of clothing or distinct weapon serves as an emblem of who I am.": "一件招牌服裝或一把獨特的武器是我身分的象徵。",
 "I never accept that I'm out of my depth.": "我從不承認自己力有未逮。",
 "I must know the answer to every secret. No door remains unopened in my presence.": "我必須知道每個祕密的答案。在我面前沒有一扇門會保持關閉。",
 "I let people underestimate me, revealing my full competency only to those close to me.": "我讓別人低估我，只向親近的人展現我全部的本事。",
 "I compulsively seek to collect trophies of my travels and victories.": "我強迫性地收集旅途與勝利的紀念品。",
 "It doesn't matter if the whole world's against me. I'll always do what I think is right.": "就算全世界都與我為敵也無所謂。我永遠會做我認為對的事。",
 "I have morbid interests and a macabre aesthetic.": "我有病態的興趣與陰森的審美觀。",
 "I have a personal ritual, mantra, or relaxation method I use to deal with stress.": "我有一套個人的儀式、咒語或放鬆方法來應對壓力。",
 "Nothing is more important than life, and I never leave anyone in danger.": "沒有什麼比生命更重要，我絕不丟下任何身陷危險的人。",
 "I'm quick to jump to extreme solutions. Why risk a lesser option not working?": "我很快就會採取極端的解決方法。何必冒險嘗試可能無效的次要選項？",
 "I'm easily startled, but I'm not a coward.": "我很容易受驚，但我不是懦夫。",
 "Adrenaline. I've experienced such strangeness that now I feel alive only in extreme situations.": "腎上腺素。我經歷過太多怪事，現在只有在極端情況下才覺得自己活著。",
 "Balance. I strive to counter the deeds of someone for whom I feel responsible.": "平衡。我努力抵銷某個我覺得自己應為其負責之人的所作所為。",
 "Bound. I've wronged someone and must work their will to avoid their curse.": "束縛。我虧待了某人，必須聽從他的意志才能避免他的詛咒。",
 "Escape. I believe there is something beyond the world I know, and I need to find it.": "逃離。我相信在我所知的世界之外還有某種東西，而我必須找到它。",
 "Legacy. I must do something great so that I'm remembered, and my time is running out.": "遺產。我必須做出一番大事才能被人記住，而我的時間所剩無幾。",
 "Misdirection. I work vigorously to keep others from realizing my flaws or misdeeds.": "誤導。我竭力不讓別人察覺我的缺點或惡行。",
 "Obsession. I've lived this way for so long that I can't imagine another way.": "執念。我這樣活了這麼久，無法想像其他的活法。",
 "Obligation. I owe it to my people, faith, family, or teacher to continue a vaunted legacy.": "義務。為了我的族人、信仰、家族或老師，我有責任延續一份備受讚譽的傳承。",
 "Promise. My life is no longer my own. I must fulfill the dream of someone who's gone.": "承諾。我的生命已不再屬於我自己。我必須完成某個逝者的夢想。",
 "Revelation. I need to know what lies beyond the mysteries of death, the world, or the Mists.": "啟示。我需要知道死亡、世界或迷霧的奧祕之外有什麼。",
 "Sanctuary. I know the forces at work in the world and strive to create islands apart from them.": "庇護。我知道世上運作的各種力量，並努力創造遠離它們的孤島。",
 "Truth. I care about the truth above all else, even if it doesn't benefit anyone.": "真相。我在乎真相勝過一切，即使它對任何人都沒有好處。",
 "I desperately need to get back to someone or someplace, but I lost them in the Mists.": "我迫切需要回到某人或某處身邊，但我在迷霧中失去了他們。",
 "Everything I do is in the service of a powerful master, one I must keep a secret from everyone.": "我所做的一切都是為了侍奉一位強大的主人，而我必須對所有人保守這個祕密。",
 "I owe much to my vanished mentor. I seek to continue their work even as I search to find them.": "我虧欠失蹤的導師很多。我一邊尋找他們，一邊努力延續他們的工作。",
 "I've seen great darkness, and I'm committed to being a light against it—the light of all lights.": "我見過巨大的黑暗，我決心成為對抗它的光——光中之光。",
 "Someone I love has become a monster, murderer, or other threat. It's up to me to redeem them.": "我所愛的人變成了怪物、殺人兇手或其他威脅。救贖他們是我的責任。",
 "The world has been convinced of a terrible lie. It's up to me to reveal the truth.": "世界被一個可怕的謊言所蒙蔽。揭露真相是我的責任。",
 "I deeply miss someone and am quick to adopt people who remind me of them.": "我深深思念某個人，很快就會接納讓我想起他們的人。",
 "A great evil dwells within me. I will fight against it and the world's other evils for as long as I can.": "一股巨大的邪惡寄宿在我體內。只要我還能，我就會對抗它以及世上其他的邪惡。",
 "I'm desperately seeking a cure to an affliction or a curse, either for someone close to me for myself.": "我拼命尋找某種病痛或詛咒的解方，可能是為了我身邊的人，也可能是為了我自己。",
 "Spirits are drawn to me. I do all I can to help them find peace.": "靈魂會被我吸引。我盡我所能幫助他們找到安息。",
 "I use my cunning mind to solve mysteries and find justice for those who've been wronged.": "我運用我機敏的頭腦解開謎團，為受冤屈的人伸張正義。",
 "I lost someone I care about, but I still see them in guilty visions, recurring dreams, or as a spirit.": "我失去了一個在乎的人，但我仍會在愧疚的幻象、反覆出現的夢境中，或以靈魂的形式看見他們。",
 "I believe doom follows me and that anyone who gets close to me will face a tragic end.": "我相信厄運跟著我，任何接近我的人都會落得悲慘的下場。",
 "I'm convinced something is after me, appearing in mirrors, dreams, and places where no one could.": "我確信有某種東西在追我，它會出現在鏡子裡、夢裡，以及沒有人能出現的地方。",
 "I'm especially superstitious and live life seeking to avoid bad luck, wicked spirits, or the Mists.": "我特別迷信，一生都在設法避開厄運、邪靈或迷霧。",
 "I've done unspeakable evil and will do anything to prevent others from finding out.": "我做過難以啟齒的惡事，會不擇手段防止別人發現。",
 "I am exceptionally credulous and believe any story or legend immediately.": "我特別容易輕信，會立刻相信任何故事或傳說。",
 "I'm a skeptic and don't believe in the power of rituals, religion, superstition, or spirits.": "我是懷疑論者，不相信儀式、宗教、迷信或靈魂的力量。",
 "I know my future is written and that anything I do will lead to a prophesied end.": "我知道我的未來已經寫好，無論我做什麼都會導向預言中的結局。",
 "I need to find the best in everyone and everything, even when that means denying obvious malice.": "我必須在每個人與每件事上找到最好的一面，即使那意味著否認明顯的惡意。",
 "I've seen the evil of a type of place—like forests, cities, or graveyards—and resist going there.": "我見識過某類地方——例如森林、城市或墓地——的邪惡，因此拒絕前往那裡。",
 "I'm exceptionally cautious, planning laboriously and devising countless contingencies.": "我特別謹慎，會費盡心思規劃，並設想無數的應變方案。",
 "I have a reputation for defeating a great evil, but that's a lie and the wicked force knows.": "我以擊敗一股巨大邪惡而聞名，但那是個謊言，而那股邪惡勢力心知肚明。",
 "I know the ends always justify the means and am quick to make sacrifices to attain my goals.": "我知道目的總能合理化手段，為了達成目標，我很快就會做出犧牲。",
};
F("bg-VRGR", [
{0: "被糾纏者", 2: "從{@skill Arcana}、{@skill Investigation}、{@skill Religion}或{@skill Survival}中選擇兩項", 4: "選擇兩種，其中一種必須是{@language Abyssal}、{@language Celestial}、{@language Deep Speech}、{@language Draconic}、{@language Infernal}、{@language Primordial}、{@language Sylvan}或{@language Undercommon}",
 6: "{@item Monster hunter's pack|VRGR}（內含一個{@item chest|PHB}、一根{@item crowbar|PHB}、一把{@item hammer|PHB}、三根木樁、一個{@item holy symbol|PHB}、一{@item Holy Water (flask)|PHB|瓶聖水}、一{@item Manacles|PHB|副鐐銬}、一面{@item steel mirror|PHB}、一{@item Oil (flask)|PHB|瓶油}、一個{@item tinderbox|PHB}與 3 支{@item Torch|PHB|火把}）、一套{@item common clothes|phb}、一件具有特殊意義的{@item trinket|CoS}（自選或在{@item Horror Trinket|VRGR|恐怖小飾品}表上擲骰），以及 1 sp",
 7: "特性：黑暗之心", 8: "看進你眼裡的人，都能看出你曾面對過難以想像的恐怖，對黑暗並不陌生。雖然他們可能害怕你，但平民會對你禮遇有加，並盡全力幫助你。除非你已表現出對他們有危險，否則若你發現自己獨自面對敵人，他們甚至會拿起武器與你並肩作戰。",
 9: "痛苦經歷", 10: "成為冒險者之前，你的人生道路是由一個黑暗的時刻、一個命運的抉擇或一場悲劇所定義的。如今你感覺到一股黑暗正威脅著要吞噬你，你擔心自己可能毫無逃脫的希望。選擇一個糾纏你的痛苦經歷，或在「痛苦經歷」表上擲骰。", 11: "痛苦經歷", 13: "經歷",
 14: "一隻屠殺了數十名無辜者的怪物饒了你一命，而你不知道為什麼。", 15: "你出生在一顆黑暗之星下。你能感覺到它冷漠而遙遠地注視著你。有時它會在深夜召喚你。", 16: "一個糾纏你家族好幾代的幽靈，如今糾纏著你。你不知道它想要什麼，而它不肯放過你。", 17: "你的家族有修習黑暗技藝的歷史。你曾涉足一次，感覺到某種可怕的東西攫住了你的靈魂，於是你驚恐地逃走了。",
 18: "在一個寒冷黑暗的夜晚，一隻鬼（Oni）帶走了你的兄弟姊妹，而你無力阻止。", 19: "你曾被詛咒成獸化人，後來被治癒了。如今你被你所屠殺的無辜者糾纏著。", 20: "一個鬼婆綁架並撫養了你。你逃了出來，但鬼婆仍以魔法控制著你，讓你的腦海充滿邪惡的念頭。", 21: "你翻開了一本異界典籍，看見了正常心智無法承受的東西。你燒掉了那本書，但它的文字與圖像已烙印在你的心靈中。",
 22: "你小時候被一個邪魔附身。你被關了起來，但逃了出來。那個邪魔仍在你體內，但如今你努力把它封住。", 23: "為了替被謀殺的心愛之人復仇，你做了可怕的事。你變成了一個怪物，這件事縈繞在你清醒時的夢境中。"},
{0: "調查員", 2: "從{@skill Insight}、{@skill Investigation}或{@skill Perception}中選擇兩項", 4: "{@item Disguise kit|phb}、{@item Thieves' tools|phb}", 6: "一個{@item magnifying glass|PHB}、一件過去案件的證物（自選或從本章稍後的{@item Horror Trinket|VRGR|恐怖小飾品}中擲骰）、一{@item Common Clothes|PHB|套平民服裝}，以及 10 gp",
 7: "特性：官方調查", 8: "你擅長接觸到能提供所需資訊的人與地點。結合巧言善辯、決心與看起來很官方的文件，你可以進入與你所調查犯罪相關的地點或接觸相關的人。與你的調查無關的人會避免妨礙你，或轉達你的請求。此外，當地執法人員對你有明確的看法，把你視為麻煩人物或自己人。",
 9: "通往謎團之路", 10: "你的第一個案子影響了你感興趣的謎團類型。為什麼這個案子如此有衝擊力、如此私人或如此令人創傷？除了你之外還影響了誰？你為何、又如何捲入其中？案子破了嗎？它如何讓你走上調查其他謎團的道路？在「第一個案子」表上擲骰或選擇細節，來發展開啟你調查員生涯的謎團。",
 11: "第一個案子", 13: "案件",
 14: "一個朋友被誣陷謀殺。你追查到真正的兇手，證明了朋友的清白，也開啟了你的偵探生涯。", 15: "有人告訴你，你失蹤了好幾個星期。被找到時，你完全不記得自己曾經離開。如今你在尋找發生在你身上的事。", 16: "你找到一個靈魂遺失的屍體，幫助它找到了安息。從那以後，其他幽靈委託人都來找你幫他們安息。",
 17: "你揭穿了恐嚇你家鄉的怪物，其實是一名殘忍法師所創造的幻象。那個施法者逃走了，但你持續揭發魔法騙局。", 18: "你被誣陷並判定犯下某項罪行。你設法逃了出來，一邊仍被法律追捕，一邊努力幫助他人避免遭受你所經歷的一切。", 19: "你在一個摧毀你家鄉的魔法裝置破壞中倖存下來。一個祕密組織的成員找到了你。你現在與他們合作，追蹤危險的超自然現象並防止它們造成傷害。",
 20: "你發現了支撐整個社會的陰謀證據。你試圖揭露這個神祕的陰謀集團，但沒有人相信你。你仍在努力證明你所知道的真相。", 21: "你在一個調查當地執法人員無法破解之罪案的機構找到了工作。你常常懷疑自己比較看重的是真相，還是薪水。"},
], HR);
