import fs from "node:fs";
import {GIANT_POT, RES_POT, RES_RING, ELEM_RING} from "./lib/common.mjs";
const HEAL = (zh, dice) => [zh, `喝下這瓶藥水時，你恢復 {@dice ${dice}} {@variantrule Hit Points|XPHB}。搖晃時，藥水的紅色液體會閃爍微光。`];
const FEATHER = (zh, ...rest) => [`誇爾的羽毛符記，${zh}`, "此物體看起來像一根羽毛。", ...rest];
const out = [
["長壽藥水","喝下這瓶藥水時，你的生理年齡減少 {@dice 1d6 + 6} 歲，最低至 13 歲。此後每次你喝下長壽藥水，都有累積 10% 的機率改為使你老化 {@dice 1d6 + 6} 歲。","這種琥珀色液體中懸浮著一顆小小的心臟，它違反一切常理地仍在跳動。打開藥水時，這些成分會消失。"],
["讀心藥水","喝下這瓶藥水時，你在 10 分鐘內獲得{@spell Detect Thoughts|XPHB}法術（豁免 {@dc 13}）的效果（無需{@status Concentration|XPHB}）。","這瓶藥水濃稠的紫色液體中漂浮著一團卵形的粉紅色雲霧。"],
RES_POT("黯蝕"),
["毒藥水","這種調製液的外觀、氣味和味道都像是{@item Potion of Healing|XDMG}或其他有益的藥水。然而，它實際上是以幻術魔法掩飾的毒藥。{@spell Identify|XPHB}能揭示其真實本質。","若你喝下這瓶藥水，你受到 {@damage 4d6} 毒素傷害，且必須通過一次 {@dc 13} 體質豁免檢定，否則處於{@condition Poisoned|XPHB}狀態 1 小時。"],
RES_POT("毒素"),
RES_POT("心靈"),
["拳擊藥水","喝下這瓶藥水後，你的每次{@variantrule Unarmed Strike|XPHB}命中時額外造成 {@damage 1d6} 力場傷害。此效果持續 10 分鐘。","這瓶藥水是一種濃稠的綠色液體，嚐起來像菠菜。"],
RES_POT("光耀"),
["速度藥水","喝下這瓶藥水時，你在 1 分鐘內獲得{@spell Haste|XPHB}法術的效果（無需{@status Concentration|XPHB}），且效果結束時不會陷入通常會出現的倦怠。","這瓶藥水的黃色液體帶有黑色條紋，並會自行旋轉。"],
GIANT_POT("石巨人", 23, "石巨人"),
GIANT_POT("風暴巨人", 29, "風暴巨人"),
HEAL("強效治療藥水", "8d4 + 8"),
HEAL("極效治療藥水", "10d4 + 20"),
RES_POT("雷鳴"),
["活力藥水","喝下這瓶藥水時，它會移除你所有的{@condition Exhaustion|XPHB}等級，並終止你身上的{@condition Poisoned|XPHB}狀態。在接下來 24 小時內，你消耗的任何{@variantrule Hit Point Dice|XPHB|生命骰}都會讓你恢復最大數量的{@variantrule Hit Points|XPHB}。","這瓶藥水的深紅色液體規律地以暗淡的光芒脈動，令人聯想到心跳。"],
["水下呼吸藥水","喝下這瓶藥水後，你可以在水下呼吸 24 小時。","這瓶藥水的混濁綠色液體帶有海洋的氣味，其中漂浮著一個像水母的氣泡。"],
["義肢","這件魔法物品可以取代失去的肢體——手、手臂、腳、腿或類似的身體部位。義肢裝上時，其功能與它所取代的部位完全相同。你可以作為一個{@action Magic|XPHB}動作卸下或重新裝上它，且在你活著時，它無法違背你的意願被取下。"],
["紫蟲毒","受到紫蟲毒影響的生物進行一次 {@dc 21} 體質豁免檢定，失敗時受到 35（{@damage 10d6}）毒素傷害，成功時傷害減半。"],
FEATHER("錨","你可以執行一個{@action Magic|XPHB}動作，將符記碰觸一艘小船或大船。在接下來 24 小時內，該船隻無法以任何方式被移動。再次用符記碰觸船隻會結束此效果。效果結束時，符記會消失。"),
FEATHER("鳥","你可以執行一個{@action Magic|XPHB}動作將符記拋向 5 呎高的空中。符記會消失，一隻巨大的彩色鳥取而代之。這隻鳥具有{@creature Roc|XMM}的數據，但無法攻擊。牠會服從你的簡單命令，以其最大速度飛行時可載重至多 500 磅（時速 16 哩，每天最多飛行 144 哩，每飛行 3 小時需休息 1 小時），或以一半的速度載重 1,000 磅。鳥在飛完一天的最大距離後，或其{@variantrule Hit Points|XPHB}降至 0 時消失。你可以作為一個{@action Magic|XPHB}動作解散這隻鳥。"),
FEATHER("扇子","若你身在小船或大船上，你可以執行一個{@action Magic|XPHB}動作將符記拋向至多 10 呎高的空中。符記會消失，一把巨大的拍動扇子取而代之。扇子會漂浮並產生強風。這陣風可以灌滿一艘船的帆，使其速度在 8 小時內增加每小時 5 哩。你可以作為一個{@action Magic|XPHB}動作解散扇子。"),
FEATHER("天鵝船","你可以執行一個{@action Magic|XPHB}動作，將符記碰觸一片直徑至少 60 呎的水域。符記會消失，一艘長 50 呎、寬 20 呎、形如天鵝的船取而代之。這艘船能自行推進，以每小時 6 哩的速度在水面上移動。在船上時，你可以執行一個{@action Magic|XPHB}動作命令它移動或轉向至多 90 度。船會存在 24 小時，然後消失。你可以作為一個{@action Magic|XPHB}動作解散這艘船。"),
FEATHER("樹","你必須身在戶外才能使用此符記。你可以執行一個{@action Magic|XPHB}動作，將它碰觸地面上的一處未被佔據空間。符記會消失，一棵非魔法的橡樹在原處憑空出現。這棵樹高 60 呎，樹幹直徑 5 呎，頂部的樹枝向外展開成 20 呎半徑。"),
FEATHER("鞭子","你可以執行一個{@action Magic|XPHB}動作，將符記投向你 10 呎內的一點。符記會消失，一條漂浮的鞭子取而代之。之後你可以執行一個{@variantrule Bonus Action|XPHB}，對鞭子 10 呎內的一個生物進行一次近戰法術攻擊，攻擊加值為 +9。命中時，目標受到 {@damage 1d6 + 5} 力場傷害。","作為一個{@variantrule Bonus Action|XPHB}，你可以指揮鞭子飛行至多 20 呎，並對鞭子 10 呎內的一個生物重複此攻擊。鞭子會在 1 小時後、你執行一個{@action Magic|XPHB}動作將其解散時，或你死亡或處於{@condition Incapacitated|XPHB}狀態時消失。"),
["特技師長棍","以此魔法武器進行的攻擊檢定與傷害擲骰獲得 +2 加值。","持有此武器時，你可以作為一個{@variantrule Bonus Action|XPHB}或在你擲{@variantrule Initiative|XPHB}後，使它發出 10 呎範圍的綠色{@variantrule Dim Light|XPHB}；你也可以作為一個{@variantrule Bonus Action|XPHB}熄滅光芒。","持有此武器時，你可以執行一個{@variantrule Bonus Action|XPHB}改變其形態，將它變成一根 6 吋長的短桿（以便收納）或一根 10 呎長竿，或變回長棍；武器只會伸長到周圍空間所允許的長度。","在某些形態下，此武器具有以下額外屬性。","特技輔助（僅限長棍與 10 呎長竿形態）","持有此武器時，你的敏捷（{@skill Acrobatics|XPHB}）檢定具有{@variantrule Advantage|XPHB}。","偏轉攻擊（僅限長棍形態）","持有此武器時被攻擊命中，你可以執行一個{@variantrule Reaction|XPHB}在身周旋轉武器，使你的{@variantrule Armor Class|XPHB}對觸發此反應的攻擊獲得 +5 加值，可能使該攻擊未命中。直到你完成一次{@variantrule Short Rest|XPHB|短休}或{@variantrule Long Rest|XPHB}前，你都無法再次使用此屬性。","遠程武器（僅限長棍形態）","此武器具有{@itemProperty T|XPHB|投擲}屬性，一般射程 30 呎，長射程 120 呎。以此武器進行遠程攻擊後，它會立即飛回你手中。"],
["石英","一顆白色、煙灰色或黃色的寶石。"],
["艾隆娜的箭袋","箭袋的三個隔層各連接到一個異次元空間，讓箭袋能容納大量物品，而重量永遠不超過 2 磅。最短的隔層可容納至多 60 支{@item Arrow|XPHB|箭}、{@item Bolt|XPHB|弩矢}或類似物體。中等的隔層可容納至多 18 支{@item Javelin|XPHB|標槍}或類似物體。最長的隔層可容納至多 6 件長形物體，例如弓、{@item Quarterstaff|XPHB|長棍}或{@item Spear|XPHB|矛}。","你可以像從普通箭袋或劍鞘中拔出一樣，拔出箭袋中的任何物品。"],
["紅龍鱗甲","{#itemEntry Dragon Scale Mail|XDMG}"],
["菱錳礦","一顆淡粉紅色的寶石。"],
RES_RING("強酸"),
["動物影響戒指","此戒指有 3 發充能，每天黎明恢復 {@dice 1d3} 發已消耗的充能。戴著戒指時，你可以消耗 1 發充能從中施展下列法術之一（豁免 {@dc 13}）：","{@spell Fear|XPHB}（僅影響野獸）"],
RES_RING("寒冷"),
["巨靈召喚戒指","戴著此戒指時，你可以執行一個{@action Magic|XPHB}動作，從氣元素位面召喚一位特定的{@creature Djinni|XMM}。氣巨靈出現在你 120 呎內一處你選擇的未被佔據空間中。只要你維持{@status Concentration|XPHB}，它就會留下，最長 1 小時，或直到其{@variantrule Hit Points|XPHB}降至 0 為止。","被召喚期間，氣巨靈對你和你的盟友{@variantrule Friendly [Attitude]|XPHB|友善}，並服從你的命令。若你沒有下達命令，氣巨靈會抵禦攻擊者，但不採取其他動作。","氣巨靈離開後，24 小時內無法再次被召喚；若氣巨靈死亡，戒指會變成非魔法物品。","巨靈召喚戒指通常由其所召喚的氣巨靈製作，並作為友誼的禮物或敬意的象徵贈予凡人。"],
ELEM_RING("氣", "氣元素位面", "氣", "你懂得氣族語，對閃電傷害具有{@variantrule Resistance|XPHB}，並擁有等同於你{@variantrule Speed|XPHB}的{@variantrule Fly Speed|XPHB}，且能懸浮。", "{@spell Chain Lightning|XPHB}（3 發充能）、{@spell Feather Fall|XPHB}（0 發充能）、{@spell Gust of Wind|XPHB}（2 發充能）、{@spell Wind Wall|XPHB}（1 發充能）"),
ELEM_RING("土", "土元素位面", "土", "你懂得土族語，並對強酸傷害具有{@variantrule Resistance|XPHB}。由碎石、岩石或泥土構成的地形對你而言不是{@variantrule Difficult Terrain|XPHB}。此外，你可以將實心泥土或岩石視為{@variantrule Difficult Terrain|XPHB}穿過其中，而不會擾動你所穿過的物質。若你在實心泥土或岩石中結束回合，你會被推到你上一次所在的最近未被佔據空間。", "{@spell Earthquake|XPHB}（5 發充能）、{@spell Stone Shape|XPHB}（2 發充能）、{@spell Stoneskin|XPHB}（3 發充能）、{@spell Wall of Stone|XPHB}（3 發充能）"),
ELEM_RING("火", "火元素位面", "火", "你懂得火族語，並對火焰傷害具有{@variantrule Immunity|XPHB}。", "{@spell Burning Hands|XPHB}（1 發充能）、{@spell Fireball|XPHB}（2 發充能）、{@spell Fire Storm|XPHB}（4 發充能）、{@spell Wall of Fire|XPHB}（3 發充能）"),
ELEM_RING("水", "水元素位面", "水", "你懂得水族語，獲得 60 呎的{@variantrule Swim Speed|XPHB}，並能在水下呼吸。", "{@spell Create or Destroy Water|XPHB}（1 發充能）、{@spell Ice Storm|XPHB}（2 發充能）、{@spell Tsunami|XPHB}（5 發充能）、{@spell Wall of Ice|XPHB}（3 發充能）、{@spell Water Walk|XPHB}（2 發充能）"),
["閃避戒指","此戒指有 3 發充能，每天黎明恢復 {@dice 1d3} 發已消耗的充能。戴著戒指時若你的敏捷豁免檢定失敗，你可以執行一個{@variantrule Reaction|XPHB}消耗 1 發充能，改為使該豁免成功。"],
["羽落戒指","戴著此戒指墜落時，你每輪下降 60 呎，且不會受到墜落傷害。"],
RES_RING("火焰"),
RES_RING("力場"),
["自由行動戒指","戴著此戒指時，{@variantrule Difficult Terrain|XPHB}不會使你消耗額外移動。此外，魔法既無法降低你的任何速度，也無法使你處於{@condition Paralyzed|XPHB}或{@condition Restrained|XPHB}狀態。"],
["隱形戒指","戴著此戒指時，你可以執行一個{@action Magic|XPHB}動作使自己處於{@condition Invisible|XPHB}狀態。你會保持{@condition Invisible|XPHB}，直到戒指被摘下，或你執行一個{@variantrule Bonus Action|XPHB}再次現形為止。"],
["跳躍戒指","戴著此戒指時，你可以從中施展{@spell Jump|XPHB}，但這麼做時只能以你自己為目標。"],
RES_RING("閃電"),
];
fs.writeFileSync(new URL("./xdmg-item-12.zh.json", import.meta.url), JSON.stringify(out));
