import fs from "node:fs";
import {VECNA, VALHALLA, VALHALLA_END} from "./lib/common.mjs";
const out = [
["火藥（桶）","點燃裝滿火藥的木桶會使其爆炸。木桶爆炸時，以木桶為中心、10 呎半徑{@variantrule Sphere [Area of Effect]|XPHB|球形}範圍內的每個生物進行一次 {@dc 12} 敏捷豁免檢定，失敗時受到 24（{@damage 7d6}）火焰傷害，成功時傷害減半。"],
["火藥（火藥角）","點燃裝滿火藥的火藥角會使其爆炸。火藥角爆炸時，以火藥角為中心、10 呎半徑{@variantrule Sphere [Area of Effect]|XPHB|球形}範圍內的每個生物進行一次 {@dc 12} 敏捷豁免檢定，失敗時受到 10（{@damage 3d6}）火焰傷害，成功時傷害減半。"],
["鬼婆之眼","鬼婆之眼有 3 發充能。穿戴或持有此物品時，你可以消耗 1 發充能施展{@spell Darkvision|XPHB}（只能以你自己為目標）或{@spell See Invisibility|XPHB}。鬼婆之眼每天黎明恢復所有已消耗的充能。","集會感應器","鬼婆之眼通常交由鬼婆的僕從保管與攜帶。作為一個{@action Magic|XPHB}動作，屬於創造該鬼婆之眼之集會的鬼婆，若與鬼婆之眼位於同一個存在位面，就能看見鬼婆之眼所見的景象。此效果持續到鬼婆停止維持{@status Concentration|XPHB}為止。集會中的多名鬼婆可以同時透過鬼婆之眼觀看。","製作鬼婆之眼","只有鬼婆集會能製作此物品，它由一顆塗上清漆的真眼製成，通常鑲在墜飾或其他可穿戴的物品上。一個鬼婆集會同時只能擁有一顆鬼婆之眼，製作新的一顆需要集會的三名成員共同舉行一場特殊儀式。此儀式需要 1 小時，若其中一名或更多鬼婆處於{@condition Incapacitated|XPHB}狀態，就無法舉行。若鬼婆們在儀式期間執行任何其他動作，儀式便會失敗並結束。"],
["維克那之手", ...VECNA("{@item Eye of Vecna|XDMG}與維克那之手是兩件獨立的神器，可能被一起或分別找到。眼睛看起來像一顆從眼窩中扯出、布滿血絲的器官。手則是一隻乾枯的左手。"),"眼與手的隨機屬性","維克那之手具有以下隨機屬性：","1 個{@table Artifact Properties; Minor Beneficial Properties|XDMG|次要有益}屬性","1 個{@table Artifact Properties; Major Beneficial Properties|XDMG|主要有益}屬性","1 個{@table Artifact Properties; Minor Detrimental Properties|XDMG|次要有害}屬性","與手同調","要與此手同調，你必須將它按在你左手原本所在的斷肢處。這隻手會嫁接在你的手臂上，成為一隻能正常運作的肢體。若這隻手被取下，你便會死亡。","手的屬性","與此手同調時，你的陣營變為中立邪惡，並獲得以下益處：","巨力","你的力量變為 20，除非它已達 20 或更高。","冰冷之觸","你以此手進行的任何近戰法術攻擊，以及以它所持武器進行的任何近戰攻擊，命中時額外造成 {@damage 2d8} 寒冷傷害。","施法","此手有 8 發充能，每天黎明恢復 {@dice 1d4 + 4} 發已消耗的充能。你可以從此手施展「{@item Hand of Vecna|XDMG}法術」表中的一道法術（豁免 {@dc 18}）。表中列出施展該法術需消耗的充能數。每次你從它施展法術時，這隻手會對你施展{@spell Suggestion|XPHB}（豁免 {@dc 18}；無需{@status Concentration|XPHB}），要求你做出一件邪惡的行為。這隻手可能心中已有特定的行為，也可能交由你決定。","維克那之手法術","法術","充能消耗","摧毀眼與手","若{@item Eye of Vecna|XDMG}與維克那之手都附著在同一個生物身上，而該生物被{@item Sword of Kas|XDMG}殺死，眼與手都會燃起火焰、化為灰燼並被摧毀。任何其他摧毀眼或手的嘗試看似有效，但神器會重新出現在維克那眾多隱藏寶庫的其中之一，等待被再次發現。"],
["鑲在彩繪木框中的手鏡"],
["易容帽","戴著這頂帽子時，你可以施展{@spell Disguise Self|XPHB}法術。若帽子被摘下，法術結束。"],
["萬法之帽","這頂尖帽具有以下屬性。","施法法器","持有此帽時，你可以將它作為你法師法術的{@variantrule Spellcasting Focus|XPHB}。你用此帽施展的任何法術都會獲得一個特殊的姿勢成分：你必須把手伸進帽子裡，把法術「拉」出來。","未知法術","持有此帽時，你可以嘗試施展一道你不知道的 1 環或更高環法術。該法術必須在法師法術列表上、必須是你能施展的環階，且其材料成分的花費不能超過 1,000 GP。決定法術後，你必須消耗一個與該法術同環階的法術欄位。接著，為了判定你是否成功施展該法術，進行一次智力（{@skill Arcana|XPHB}）檢定（{@dc 10} + 法術環階）。檢定成功時，你以其正常施法時間施展該法術，且直到你完成一次{@variantrule Short Rest|XPHB|短休}或{@variantrule Long Rest|XPHB}前都無法再次使用此屬性。檢定失敗時，你未能施展該法術，改為發生一個隨機效果，在下表擲骰決定。","你從帽子施展的任何法術都使用你的法術豁免 DC 與法術攻擊加值。","1d100","效果","你施展一道由擲 {@dice 1d10} 決定的隨機法術：{@b 1}，{@spell Enlarge/Reduce|XPHB}（變大效果）；{@b 2}，{@spell Enlarge/Reduce|XPHB}（變小效果）；{@b 3}，{@spell Faerie Fire|XPHB}；{@b 4}，{@spell Fireball|XPHB}；{@b 5}，{@spell Gust of Wind|XPHB}；{@b 6}，{@spell Invisibility|XPHB}（對你自己施展）；{@b 7}，{@spell Lightning Bolt|XPHB}；{@b 8}，{@spell Phantasmal Force|XPHB}；{@b 9}，{@spell Polymorph|XPHB}；{@b 10}，{@spell Stinking Cloud|XPHB}。","你處於{@condition Stunned|XPHB}狀態直到你的下個回合結束，你以為剛剛發生了什麼了不起的事。","一群無害的蝴蝶填滿你 30 呎內的一個 10 呎{@variantrule Cube [Area of Effect]|XPHB|立方}範圍。蝶群在 1 分鐘後散去。","你從帽子裡拉出一件非魔法物體。擲 {@dice 1d4} 決定物體：{@b 1}，一瓶強酸；{@b 2}，一瓶煉金之火；{@b 3}，一根撬棍；{@b 4}，一支點燃的火炬。","你發作一陣「魔法病」，處於{@condition Poisoned|XPHB}狀態 1 小時。","你處於{@condition Petrified|XPHB}狀態直到你的下個回合結束。","你從帽子裡拉出一件非魔法物體。擲 {@dice 1d4} 決定物體：{@b 1}，一把{@item Dagger|XPHB}；{@b 2}，一條一端綁著{@item Grappling Hook|XPHB}的{@item Rope|XPHB}；{@b 3}，一袋{@item Caltrops|XPHB}；{@b 4}，一顆價值 50 GP 的寶石。","一個生物出現在盡可能靠近你的未被佔據空間中。該生物不受你控制，會按其平常的方式行動，並在 1 小時後或其{@variantrule Hit Points|XPHB}降至 0 時消失。擲 {@dice 1d4} 決定生物：{@b 1}，一隻{@creature Camel|XMM}；{@b 2}，一條{@creature Constrictor Snake|XMM}；{@b 3}，一頭{@creature Elephant|XMM}；{@b 4}，一頭{@creature Mule|XMM}。","一群{@variantrule Hostile [Attitude]|XPHB|敵對}的{@creature Swarm of Bats|XMM}從帽子裡飛出，佔據你的空間並攻擊你。","一道直徑 10 呎、垂直的雙向傳送門在你 30 呎內的未被佔據空間中開啟，通往另一個存在位面，並持續開啟到你的下個回合結束。它通往何處由 DM 決定。","你從帽子裡拉出一件魔法物品。擲 {@dice 1d6} 決定物品的稀有度：{@b 1-3}，{@filter 普通|items|rarity=Common}；{@b 4-5}，{@filter 非普通|items|rarity=Uncommon}；{@b 6}，{@filter 珍稀|items|rarity=Rare}。物品由 DM 選擇，若在 1 小時內未被消耗或摧毀，便會消失。"],
["害蟲之帽","這頂帽子有 3 發充能。持有帽子時，你可以執行一個{@action Magic|XPHB}動作消耗 1 發充能，召喚一隻由你選擇的{@creature Bat|XMM}、{@creature Frog|XMM}或{@creature Rat|XMM}。被召喚的生物以魔法出現在帽子裡，並試圖盡快逃離你。該生物對你和其他生物{@variantrule Indifferent [Attitude]|XPHB|冷淡}，且不受你控制。它的行為與同類的普通生物一樣，並在 1 小時後或其{@variantrule Hit Points|XPHB}降至 0 時消失。帽子每天黎明恢復所有已消耗的充能。"],
["巫術帽","這頂圓錐形帽子上裝飾著月亮與星星。戴著它時，你獲得以下益處。","施法法器","你可以將此帽作為你法師法術的{@variantrule Spellcasting Focus|XPHB}。","未知法術","作為一個{@action Magic|XPHB}動作，你可以嘗試施展一道你不知道的戲法。該戲法必須在法師法術列表上且施法時間為一個動作，你進行一次 {@dc 10} 智力（{@skill Arcana|XPHB}）檢定。檢定成功時，你施展該法術。檢定失敗時，法術失敗，用來施展它的動作也被浪費。無論成功與否，直到你完成一次{@variantrule Long Rest|XPHB}前，你都無法再次使用此屬性。"],
["智力頭帶","戴著這條頭帶時，你的智力值為 19。若你不戴它時智力已達 19 或更高，則它對你沒有效果。"],
["光輝頭盔","此頭盔鑲有 {@dice 1d10} 顆鑽石、{@dice 2d10} 顆紅寶石、{@dice 3d10} 顆火蛋白石與 {@dice 4d10} 顆蛋白石。從頭盔上撬下的任何寶石都會碎成粉末。當所有寶石都被取下或摧毀時，頭盔會失去魔力。","戴著頭盔時，你獲得以下益處。","鑽石之光","只要頭盔上至少有一顆鑽石，它就會發出 30 呎{@variantrule Emanation [Area of Effect]|XPHB|散發}範圍。當該區域內至少有一個不死生物時，{@variantrule Emanation [Area of Effect]|XPHB|散發}範圍會充滿{@variantrule Dim Light|XPHB}。任何在該區域內開始其回合的不死生物受到 {@damage 1d6} 光耀傷害。","火蛋白石之焰","只要頭盔上至少有一顆火蛋白石，你就可以執行一個{@action Magic|XPHB}動作，使你持有的一把武器燃起火焰。火焰在 10 呎半徑內發出{@variantrule Bright Light|XPHB}，並在其外額外 10 呎發出{@variantrule Dim Light|XPHB}。火焰對你和武器無害。當你以燃燒的武器攻擊命中時，目標額外受到 {@damage 1d6} 火焰傷害。火焰持續到你執行一個{@variantrule Bonus Action|XPHB}將其熄滅，或你放下或收起武器為止。","紅寶石抗性","只要頭盔上至少有一顆紅寶石，你就對火焰傷害具有{@variantrule Resistance|XPHB}。","法術","你可以施展下列法術之一（豁免 {@dc 18}），以頭盔上一顆指定種類的寶石作為成分：{@spell Daylight|XPHB}（蛋白石）、{@spell Fireball|XPHB}（火蛋白石）、{@spell Prismatic Spray|XPHB}（鑽石）或{@spell Wall of Fire|XPHB}（紅寶石）。施展法術時，該寶石會被摧毀並從頭盔上消失。","受到火焰傷害","若你戴著頭盔並因法術豁免失敗而受到火焰傷害，擲 {@dice 1d20}。擲出 1 時，頭盔會從其剩餘的寶石射出光束，然後被摧毀。從你發出的 60 呎{@variantrule Emanation [Area of Effect]|XPHB|散發}範圍內的每個生物必須通過一次 {@dc 17} 敏捷豁免檢定，否則被光束擊中，受到等同於頭盔上寶石數量的光耀傷害。"],
["通曉語言頭盔","戴著這頂頭盔時，你可以從中施展{@spell Comprehend Languages|XPHB}。"],
["心靈感應頭盔","戴著這頂頭盔時，你擁有範圍 30 呎的心靈感應，並可以從頭盔施展{@spell Detect Thoughts|XPHB}或{@spell Suggestion|XPHB}（豁免 {@dc 13}）。從頭盔施展其中任一法術後，直到下一個黎明前都無法再從頭盔施展該法術。"],
["傳送頭盔","此頭盔有 3 發充能。戴著它時，你可以消耗 1 發充能從中施展{@spell Teleport|XPHB}。頭盔每天黎明恢復 {@dice 1d3} 發已消耗的充能。"],
["赤鐵礦","一顆灰黑色的寶石。"],
["霍華德的便利背包","這個背包有一個中央袋和兩個側袋，每個都是一個異次元空間。每個側袋可容納至多 200 磅的物品，體積不超過 25 立方呎。中央袋可容納至多 500 磅的物品，體積不超過 64 立方呎。無論裝了什麼，背包總是重 5 磅。","從背包中取出一件物品需要一個{@action Utilize|XPHB}動作或一個{@variantrule Bonus Action|XPHB}（由你選擇）。當你伸手到背包中找某件特定物品時，該物品總會以魔法方式出現在最上面。","若任一袋子超載、被刺穿或撕裂，背包會破裂並被摧毀。若背包被摧毀，其內容物會永遠消失，但神器總會在某處再次出現。若背包被裡外翻轉，其內容物會完好無損地傾瀉而出，而背包必須翻回原狀才能再次使用。","背包的每個袋子中的空氣足夠呼吸 10 分鐘，除以袋內會呼吸的生物數量。","將此背包放入由{@item Bag of Holding|XDMG}、{@item Portable Hole|XDMG}或類似物品所創造的異次元空間中，會立即摧毀兩件物品，並開啟一道通往星界的傳送門。傳送門出現在其中一件物品被放入另一件物品的位置。傳送門 10 呎內任何未處於{@variantrule Cover|XPHB|全掩護}後方的生物，都會被吸入傳送門並被送到星界的一個隨機地點。之後傳送門關閉。此傳送門是單向的，且無法再次開啟。"],
["霍華德的便利香料袋","這個腰包看起來是空的，有 10 發充能。持有此袋時，你可以執行一個{@action Magic|XPHB}動作消耗 1 發充能，說出任何一種非魔法的食物調味料（例如鹽、胡椒、番紅花或香菜），並從袋中取出一撮所需的調味料。一撮足夠為一餐調味。此袋每天黎明恢復 {@dice 1d6 + 4} 發已消耗的充能。"],
["爆破號角","你可以執行一個{@action Magic|XPHB}動作吹響此號角，在 30 呎{@variantrule Cone [Area of Effect]|XPHB|錐形}範圍內發出雷鳴般的爆音，600 呎外都能聽見。{@variantrule Cone [Area of Effect]|XPHB|錐形}範圍內的每個生物進行一次 {@dc 15} 體質豁免檢定。豁免失敗時，生物受到 {@damage 5d8} 雷鳴傷害，並處於{@condition Deafened|XPHB}狀態 1 分鐘。豁免成功時，生物只受到一半傷害。{@variantrule Cone [Area of Effect]|XPHB|錐形}範圍內未被穿戴或攜帶的玻璃或水晶物體受到 {@damage 10d8} 雷鳴傷害。","每次使用號角的魔法，都有 {@chance 20} 的機率使號角爆炸。爆炸會對使用者造成 {@damage 10d6} 力場傷害，並摧毀號角。"],
["無聲警報號角","此號角有 4 發充能，每天黎明恢復 {@dice 1d4} 發已消耗的充能。作為一個{@action Magic|XPHB}動作，你可以消耗 1 發充能吹響號角。一個由你選擇、位於號角 600 呎內的生物會聽見號角的鳴響。其他生物都聽不見。"],
["瓦爾哈拉號角，黃銅", ...VALHALLA, "黃銅號角召喚 3 名{@creature Berserker|XMM|狂戰士}。要使用黃銅號角，你必須擁有所有簡易武器的{@variantrule Proficiency|XPHB|熟練}。", VALHALLA_END],
["瓦爾哈拉號角，青銅", ...VALHALLA, "青銅號角召喚 4 名{@creature Berserker|XMM|狂戰士}。要使用青銅號角，你必須受過所有中甲的訓練。", VALHALLA_END],
];
fs.writeFileSync(new URL("./xdmg-item-08.zh.json", import.meta.url), JSON.stringify(out));
