import fs from "node:fs";
import {VALHALLA, VALHALLA_END, BARD, BARD_END, BARD_BASE, HORSESHOE} from "./lib/common.mjs";
const bard = (zh, playName, rest) => [`吟遊詩人樂器，${zh}`, BARD, `你可以演奏${playName}來施展下列法術之一：${BARD_BASE}、${rest}。${BARD_END(playName)}`];
const IOUN = (name, text) => [`艾恩石，${name}`, "{#itemEntry Ioun Stone|XDMG}", text];
const out = [
["瓦爾哈拉號角，黑鐵", ...VALHALLA, "黑鐵號角召喚 5 名{@creature Berserker|XMM|狂戰士}。要使用黑鐵號角，你必須擁有所有軍用武器的{@variantrule Proficiency|XPHB|熟練}。", VALHALLA_END],
["瓦爾哈拉號角，白銀", ...VALHALLA, "白銀號角召喚 2 名{@creature Berserker|XMM|狂戰士}。他們對你和你的盟友{@variantrule Friendly [Attitude]|XPHB|友善}，並聽從你的命令。"],
["西風馬蹄鐵", HORSESHOE, "當四個馬蹄鐵都固定在一匹馬或類似生物的蹄上時，它們讓該生物能在離表面 4 吋處漂浮並正常移動。這表示該生物可以在非固體或不穩定的表面（例如水或熔岩）上穿越或站立。該生物不會留下足跡，並無視{@variantrule Difficult Terrain|XPHB}。此外，該生物每天可以旅行至多 12 小時，而不會因長途旅行而獲得{@condition Exhaustion|XPHB}等級。"],
["加速馬蹄鐵", HORSESHOE, "當四個馬蹄鐵都附著在同一個生物身上時，其{@variantrule Speed|XPHB}增加 30 呎。"],
["不動權杖","這根鐵杖的一端有一個按鈕。你可以執行一個{@action Utilize|XPHB}動作按下按鈕，使權杖以魔法固定在原處。直到你或另一個生物執行一個{@action Utilize|XPHB}動作再次按下按鈕之前，權杖都不會移動，即使這違反重力。權杖可以承受至多 8,000 磅的重量。更重的重量會使權杖停止作用並掉落。生物可以執行一個{@action Utilize|XPHB}動作進行一次 {@dc 30} 力量（{@skill Athletics|XPHB}）檢定，成功時可將固定的權杖移動至多 10 呎。"],
["幻象樂器","演奏這件{@item musical instrument|XPHB|樂器}時，你可以執行一個{@action Magic|XPHB}動作，在從樂器發出的 5 呎{@variantrule Emanation [Area of Effect]|XPHB|散發}範圍內創造無害的幻象視覺效果。若你是吟遊詩人，{@variantrule Emanation [Area of Effect]|XPHB|散發}範圍增加到 15 呎。視覺效果的例子包括發光的音符、幽靈舞者、蝴蝶以及輕輕飄落的雪花。這些魔法效果既無實體也無聲音，明顯是幻象。當你停止演奏時，效果結束。"],
["書寫樂器","這件{@item musical instrument|XPHB|樂器}有 3 發充能，每天黎明恢復所有已消耗的充能。演奏它時，你可以執行一個{@action Magic|XPHB}動作消耗 1 發充能，在你 30 呎內一個你能看見的非魔法物體或表面上寫下一則魔法訊息。訊息最多可以有六個字，並以你所知的一種語言寫成。若你是吟遊詩人，你可以額外書寫七個字，並使訊息發出微光，使其在非魔法的{@variantrule Darkness|XPHB}中也能被看見。對訊息施展{@spell Dispel Magic|XPHB}法術會將其抹除。否則，訊息會在 24 小時後逐漸消失。"],
bard("安斯楚斯豎琴","安斯楚斯豎琴","{@spell Cure Wounds|XPHB}（5 環）、{@spell Ice Storm|XPHB}與{@spell Wall of Thorns|XPHB}"),
bard("卡奈斯曼陀林","卡奈斯曼陀林","{@spell Cure Wounds|XPHB}（3 環）、{@spell Dispel Magic|XPHB}與{@spell Protection from Energy|XPHB}（僅限閃電傷害）"),
["吟遊詩人樂器，克里里拉琴", BARD, "你可以演奏克里{@item Lyre|XPHB|里拉琴}來施展下列法術之一：" + BARD_BASE + "、{@spell Stone Shape|XPHB}、{@spell Wall of Fire|XPHB}與{@spell Wind Wall|XPHB}。一旦克里{@item Lyre|XPHB|里拉琴}被用來施展某道法術，直到下一個黎明前都無法再用它施展該法術。這些法術使用你的施法屬性與法術豁免 DC。"],
["吟遊詩人樂器，多斯魯特琴", BARD, "你可以演奏多斯{@item Lute|XPHB|魯特琴}來施展下列法術之一：" + BARD_BASE + "、{@spell Animal Friendship|XPHB}、{@spell Protection from Energy|XPHB}（僅限火焰傷害）與{@spell Protection from Poison|XPHB}。一旦多斯{@item Lute|XPHB|魯特琴}被用來施展某道法術，直到下一個黎明前都無法再用它施展該法術。這些法術使用你的施法屬性與法術豁免 DC。"],
bard("佛克路坎班多拉琴","佛克路坎班多拉琴","{@spell Entangle|XPHB}、{@spell Faerie Fire|XPHB}、{@spell Shillelagh|XPHB}與{@spell Speak with Animals|XPHB}"),
bard("麥克弗米德西特琴","麥克弗米德西特琴","{@spell Barkskin|XPHB}、{@spell Cure Wounds|XPHB}與{@spell Fog Cloud|XPHB}"),
bard("奧拉姆豎琴","奧拉姆豎琴","{@spell Confusion|XPHB}、{@spell Control Weather|XPHB}與{@spell Fire Storm|XPHB}"),
IOUN("吸收","當這顆淡紫色橢球繞著你的頭部運行時，你可以執行一個{@variantrule Reaction|XPHB}，取消一個你能看見的生物所施展的 4 環或更低環法術。被取消的法術沒有效果，施展它所用的任何資源都會被浪費。一旦此石取消了總計 20 環的法術，它就會燃盡、變成暗灰色並失去魔力。"),
IOUN("敏捷","當這顆深紅色球體繞著你的頭部運行時，你的敏捷提升 2，最高至 20。"),
IOUN("警覺","當這顆深藍色菱形體繞著你的頭部運行時，你的{@variantrule Initiative|XPHB}擲骰與感知（{@skill Perception|XPHB}）檢定具有{@variantrule Advantage|XPHB}。"),
IOUN("堅韌","當這顆粉紅色菱形體繞著你的頭部運行時，你的體質提升 2，最高至 20。"),
IOUN("強效吸收","當這顆淡紫與綠色大理石紋橢球繞著你的頭部運行時，你可以執行一個{@variantrule Reaction|XPHB}，取消一個你能看見的生物所施展的 8 環或更低環法術。被取消的法術沒有效果，施展它所用的任何資源都會被浪費。一旦此石取消了總計 20 環的法術，它就會燃盡、變成暗灰色並失去魔力。"),
IOUN("洞察","當這顆熾亮藍色球體繞著你的頭部運行時，你的感知提升 2，最高至 20。"),
IOUN("智力","當這顆猩紅與藍色大理石紋球體繞著你的頭部運行時，你的智力提升 2，最高至 20。"),
IOUN("領導","當這顆粉紅與綠色大理石紋球體繞著你的頭部運行時，你的魅力提升 2，最高至 20。"),
IOUN("精通","當這顆淡綠色稜柱繞著你的頭部運行時，你的{@variantrule Proficiency|XPHB|熟練加值}增加 1。"),
IOUN("防護","當這顆灰玫瑰色稜柱繞著你的頭部運行時，你的{@variantrule Armor Class|XPHB}獲得 +1 加值。"),
IOUN("再生","若你至少有 1 點{@variantrule Hit Points|XPHB|生命值}，這顆珍珠白紡錘體繞著你的頭部運行期間，你在每小時結束時恢復 15 點{@variantrule Hit Points|XPHB}。"),
["艾恩石，儲存","{#itemEntry Ioun Stone|XDMG}","這顆鮮豔的紫色稜柱會儲存施入其中的法術，保存到你使用為止。此石一次最多可儲存 4 環的法術。被找到時，其中儲存有 {@dice 1d4} 環由 DM 選擇的法術。","任何生物都可以在施法時碰觸此石，將一道 1 至 4 環的法術施入石中。該法術除了被儲存在石中之外沒有任何效果。若此石無法容納該法術，法術會被消耗而沒有效果。施展法術所用的法術欄位環階決定它佔用多少空間。","當此石繞著你的頭部運行時，你可以施展儲存在其中的任何法術。該法術使用原施法者的欄位環階、法術豁免 DC、法術攻擊加值與施法屬性，但除此之外視為由你施展。從石中施展的法術不再儲存於其中，騰出空間。"],
IOUN("力量","當這顆淡藍色菱形體繞著你的頭部運行時，你的力量提升 2，最高至 20。"),
IOUN("維生","當這顆透明紡錘體繞著你的頭部運行時，你不需要進食或飲水。"),
["鐵"],
["比拉羅的鐵箍","這顆生鏽的鐵球直徑 3 吋，重 1 磅。你可以執行一個{@action Magic|XPHB}動作，將鐵球投向你 60 呎內一個你能看見的超大型或更小的生物。鐵球在空中飛行時會展開成一團糾結的金屬箍。","進行一次遠程攻擊檢定，攻擊加值等同於你的敏捷調整值 + 你的{@variantrule Proficiency|XPHB|熟練加值}。命中時，目標處於{@condition Restrained|XPHB}狀態，直到你執行一個{@variantrule Bonus Action|XPHB}下達命令將其釋放。這麼做或攻擊未命中時，鐵箍會收縮並再次變回球體。","能碰觸到鐵箍的生物（包括被{@condition Restrained|XPHB}的生物）可以執行一個動作進行一次 {@dc 20} 力量（{@skill Athletics|XPHB}）檢定來扯斷鐵箍。檢定成功時，物品被摧毀，{@condition Restrained|XPHB}的生物獲得自由。檢定失敗時，該生物在 24 小時內進行的任何後續嘗試都會自動失敗。","鐵箍使用後，直到下一個黎明前都無法再次使用。"],
["鐵瓶","持有這個黃銅瓶塞的鐵瓶時，你可以執行一個{@action Magic|XPHB}動作，以你 60 呎內一個你能看見的生物為目標。若瓶子是空的，且目標原生於你所在位面以外的另一個存在位面，目標必須通過一次 {@dc 17} 感知豁免檢定，否則被困入瓶中。若目標曾被此瓶困住過，它在豁免上具有{@variantrule Advantage|XPHB}。生物一旦被困住，就會留在瓶中直到被釋放。瓶子一次只能容納一個生物。被困在瓶中的生物不會老化，也不需要呼吸、進食或飲水。","你可以執行一個{@action Magic|XPHB}動作拔開瓶塞，釋放瓶中的生物。之後該生物會服從你的命令 1 小時，即使它不懂下達命令所用的語言，也能理解那些命令。若你沒有下達命令，或給予該生物一個可能導致其死亡或被囚禁的命令，它會自我防衛，但除此之外不採取任何動作。持續時間結束時，該生物會依其平常的性情與陣營行動。","{@spell Identify|XPHB}法術能揭示瓶中是否有生物，但確定生物種類的唯一方法是打開瓶子。新發現的鐵瓶中可能已經裝有一個由 DM 選擇或在下表隨機擲骰決定的生物（該生物的數據資料見{@book 怪物圖鑑|XMM}）。","1d100","內容物","沒有生物"],
["紅鋯石","一顆火橙色的寶石。"],
["翡翠","一顆淺綠色、深綠色或白色的寶石。"],
["附黃金棋子的翡翠棋盤"],
["碧玉","一顆藍色、黑色或棕色的寶石。"],
["閃電標槍","每次你以此魔法武器進行攻擊檢定並命中時，你可以讓它造成閃電傷害而非穿刺傷害。","閃電束","當你將此武器投向距離你不超過 120 呎的目標時，你可以放棄進行遠程攻擊檢定，改為將武器化為一道閃電。這道閃電在你與目標之間形成一條寬 5 呎的{@variantrule Line [Area of Effect]|XPHB|直線}。目標以及{@variantrule Line [Area of Effect]|XPHB|直線}範圍內的其他每個生物（你除外）進行一次 {@dc 13} 敏捷豁免檢定，失敗時受到 {@damage 4d6} 閃電傷害，成功時傷害減半。造成此傷害後，武器立即重新出現在你手中。直到下一個黎明前，都無法再次使用此屬性。"],
["煤玉","一顆深黑色的寶石。"],
["鑲有珠寶的腳鍊"],
["鑲有珠寶的黃金王冠"],
["鑲有珠寶的白金戒指"],
];
fs.writeFileSync(new URL("./xdmg-item-09.zh.json", import.meta.url), JSON.stringify(out));
