import F from "./_fillidx.mjs";
const BS = "你在戰鬥中受到神聖力量的祝福。當一個生物受到你的戲法或武器攻擊的傷害時，你也可以對該生物造成 {@damage 1d8} 光耀傷害。造成此傷害後，直到你的下個回合開始前都無法再次使用此特性。";
const D = {
 "Blessed Strikes": "神佑打擊", "Order Domain": "秩序領域",
 "You are blessed with divine might in battle. When a creature takes damage from one of your cantrips or weapon attacks, you can also deal {@damage 1d8} radiant damage to that creature. Once you deal this damage, you can't use this feature again until the start of your next turn.": BS,
 "{@i 8th-level cleric {@variantrule optional class features|tce|optional feature}, which replaces the Divine Strike feature}": "{@i 8 級牧師{@variantrule optional class features|tce|選用特性}，取代神聖打擊特性}",
 "{@i 8th-level cleric {@variantrule optional class features|tce|optional feature}, which replaces the Potent Spellcasting feature}": "{@i 8 級牧師{@variantrule optional class features|tce|選用特性}，取代強效施法特性}",
 "Channel Divinity: Balm of Peace": "引導神力：和平香膏", "Channel Divinity: Twilight Sanctuary": "引導神力：暮光聖所",
 "Example Deity": "神祇範例", "Pantheon": "神系", "Elven": "精靈", "Dwarven": "矮人", "Eberron": "艾伯倫", "Forgotten Realms": "被遺忘國度", "Gnomish": "地侏", "Dragonlance": "龍槍", "Greyhawk": "灰鷹", "Domain Spells": "領域法術",
};
const DS = n => `你在「${n}法術」表所列的牧師等級獲得領域法術。關於領域法術的運作方式，請見神聖領域職業特性。`;
F("scf-TCE-Cleric", [
{1: "你獲得軍用武器與重甲的熟練。"},
{0: "鼓舞羈絆", 1: "你能在彼此和平相處的人們之間建立賦予力量的羈絆。作為一個動作，你選擇你 30 呎內數量等同於你熟練加值的自願生物（可以包括你自己）。你在他們之間建立一道持續 10 分鐘的魔法羈絆，或直到你再次使用此特性為止。當任何受羈絆的生物位於另一個受羈絆生物 30 呎內時，該生物進行攻擊檢定、屬性檢定或豁免檢定時，可以擲一顆 {@dice d4} 並將結果加到檢定上。每個生物每回合最多只能加一次這顆 {@dice d4}。"},
{0: "夜之眼", 1: "你能看穿最深沉的幽暗。你擁有範圍 300 呎的{@sense darkvision}。在此範圍內，你能在微光中視物如同在明亮光照中一樣，在黑暗中視物如同在微光中一樣。",
 2: "作為一個動作，你可以用魔法將此特性的{@sense darkvision}分享給你 10 呎內你能看見的自願生物，數量至多等同於你的感知調整值（至少一個生物）。分享的{@sense darkvision}持續 1 小時。分享後，除非你消耗任意環階的法術欄位再次分享，否則直到你完成長休前都無法再次這麼做。"},
{0: "和平之器", 1: "你獲得{@skill Insight}、{@skill Performance}或{@skill Persuasion}技能（由你選擇）的熟練。"},
{0: "秩序領域", 1: "秩序領域代表紀律，以及對社會或機構的忠誠，與對其法律的嚴格服從。在拉尼卡，此領域受到阿佐理斯議會的牧師青睞，他們用它來維護與執行法律；歐佐夫教會的牧師也偏好此領域，他們利用法律與秩序謀取私利。在其他世界，賦予此領域的神祇包括{@deity Bane}、{@deity Tyr}、{@deity Majere|Dragonlance}、{@deity Erathis|Dawn War|DMG}、{@deity Pholtus|Greyhawk}、{@deity Wee Jas|Greyhawk}、{@deity Aureon|Eberron}、{@deity Maglubiyet|Nonhuman}、{@deity Nuada|Celtic}、{@deity Athena|Greek}、{@deity Anubis|Egyptian}、{@deity Forseti|Norse}與{@deity Asmodeus|Dawn War|DMG}。",
 2: "秩序的理想是對法律的服從高於一切，而非對特定個人、一時的情緒或民意的服從。秩序牧師通常關心事情是如何完成的，而非行動的結果是否公正。遵守法律並服從其律令至關重要，特別是當這麼做對這些牧師及其公會或神祇有利時。",
 3: "法律建立階級。被法律選為領導者的人必須被服從。服從者必須盡其所能地服從。以這種方式，法律創造出錯綜複雜的義務網絡，讓社會得以在混亂的多元宇宙中建立秩序與安全。",
 4: "在每個標示的牧師等級，你將所列的法術加入你的已準備法術中。", 5: "秩序領域法術"},
{1: "和平的香膏在健全社群的核心、友好國家之間，以及善良之人的靈魂中蓬勃發展。和平之神激勵各式各樣的人解決衝突，並挺身對抗那些試圖阻止和平興盛的力量。與此領域相關的一些神祇，請見「和平神祇」表。",
 2: "和平領域的牧師主持條約的簽署，也常被請來仲裁紛爭。這些牧師的祝福讓人們團結在一起，幫助他們分擔彼此的重擔，而牧師的魔法則協助那些為和平之道而戰的人。",
 3: "和平神祇", 15: DS("和平領域"), 16: "和平領域法術"},
{1: "從光明轉入黑暗的暮光時分，常帶來平靜甚至喜悅，因為一天的勞動結束，休息的時刻開始了。黑暗也可能帶來恐懼，但暮光之神會守護人們免受夜晚的恐怖侵擾。",
 2: "侍奉這些神祇（範例見「暮光神祇」表）的牧師，為尋求休息的人帶來慰藉，並冒險深入逼近的黑暗來保護他們，確保黑暗是一種慰藉，而非恐懼。",
 3: "暮光神祇", 15: DS("暮光領域"), 16: "暮光領域法術"},
{0: "警覺祝福", 1: "黑夜教會了你保持警覺。作為一個動作，你讓一個你碰觸的生物（可以是你自己）在其下一次先攻擲骰上具有優勢。此益處在擲骰後立即結束，或在你再次使用此特性時結束。"},
{2: "你可以使用引導神力，讓你的存在本身成為撫慰人心的香膏。作為一個動作，你可以移動至多等同於你速度的距離，且不會引發借機攻擊；在此動作中，當你移動到任何其他生物 5 呎內時，你可以為該生物恢復等同於 {@dice 2d6} + 你感知調整值的生命值（至少 1 點生命值）。每次你執行此動作時，一個生物只能接受一次此治療。"},
{2: "你可以使用引導神力，以撫慰人心的暮光讓你的盟友恢復精神。",
 3: "作為一個動作，你展示你的聖徽，一道暮光球體從你身上散發出來。球體以你為中心，半徑 30 呎，充滿微光。球體隨你移動，持續 1 分鐘，或直到你{@condition incapacitated}或死亡為止。每當一個生物（包括你）在球體中結束其回合時，你可以給予該生物下列益處之一：",
 4: "你給予它等同於 {@dice 1d6} 加上你牧師等級的臨時生命值。", 5: "你結束它身上一個使其{@condition charmed}或{@condition frightened}的效果。"},
{}, {}, {}, {}, {},
{0: "保護羈絆", 1: "你在人們之間建立的羈絆，幫助他們互相保護。當一個受你鼓舞羈絆特性影響的生物即將受到傷害時，位於第一個生物 30 呎內的第二個受羈絆生物可以使用其反應，傳送到第一個生物 5 呎內的一處未被佔據空間。接著由第二個生物承受全部傷害。"},
{0: "夜之步", 1: "你能汲取夜晚的神祕力量升上天空。當你身處微光或黑暗中時，你可以作為附贈動作，以魔法使自己獲得等同於步行速度的飛行速度，持續 1 分鐘。你可以使用此附贈動作的次數等同於你的熟練加值，並在完成長休時恢復所有已消耗的使用次數。"},
...Array(18).fill({}),
{1: "你獲得將神聖能量灌注到武器打擊中的能力。在你的每個回合中一次，當你以武器攻擊命中一個生物時，你可以使該攻擊額外造成 {@damage 1d8} 光耀傷害。當你達到 14 級時，額外傷害增加到 {@damage 2d8}。"},
{1: "你將感知調整值加到你以任何牧師戲法造成的傷害上。"},
{0: "擴展羈絆", 1: "現在當受羈絆的生物彼此相距 60 呎內時，你的鼓舞羈絆與保護羈絆特性的益處就能生效。此外，當一個生物使用保護羈絆承受他人的傷害時，該生物對該傷害具有抗性。"},
{0: "暮光帷幕", 1: "你召喚的暮光提供了保護的懷抱：位於你暮光聖所所創造的球體中時，你與你的盟友具有{@quickref Cover||3||半遮蔽}。"},
], D);
