import F from "./_fillidx.mjs";
import {D as D1, M1, LR} from "./_scfFR1.mjs";
const R = "{@variantrule Reaction|XPHB}", EM = n => `源自你的 ${n} 呎{@variantrule Emanation [Area of Effect]|XPHB|發散}`;
const D = {...D1, "Spellfire Sorcery": "法術火術法", "Spellfire Spells": "法術火法術", "Training in War and Song": "戰爭與歌唱訓練", "Winter Walker": "寒冬行者",
 "Winter Walker Spells": "寒冬行者法術", "Absorb Spells": "吸收法術", "Blessing of Moonlight": "月光祝福", "Unfettered Mind": "無拘心智",
 "Aura of Elemental Shielding": "元素護盾靈光", "Fortifying Soul": "堅毅之魂", "Team Tactics": "團隊戰術", "Strike Fear": "恐懼打擊", "Rallying Surge": "集結奔湧",
 "Song of Defense": "防禦之歌", "Chilling Retribution": "寒冷報復", "Aura of Malevolence": "惡意靈光", "Eventide's Splendor": "暮色輝煌", "Honed Spellfire": "精煉法術火",
 "Song of Victory": "勝利之歌", "Elemental Rebuke": "元素斥責", "Frozen Haunt": "冰凍幽魂", "Shared Resilience": "共享韌性", "Divine Foreknowledge": "神聖預知",
 "Dread Incarnate": "恐懼化身", "Crown of Spellfire": "法術火之冠", "Inspiring Commander": "激勵指揮官", "Noble Scion": "貴族後裔"};
F("scf-FRHoF", [...M1,
{1: "你的天生力量源自魔法的根源本身：魔網。此連結以一種被稱為法術火的罕見能力顯現，你湧動著這種原始魔法的光輝爆發。你對法術火的天賦讓你能治療盟友、灼燒敵人，並吸收強大的法術。",
 2: "法術火的使用者往往喜愛漫遊。許多人在國際化的聚落之間旅行，例如劍灣沿岸的那些聚落，並以他們的魔法服務於公眾利益。另一些人則藉由漫遊同樣奇異的土地來了解自己奇異的力量，從被魔法摧殘的阿納羅克沙漠荒原，到受神祇觸碰的古帝國荒野皆然。無論他們前往國度的何處，法術火術士都會受到對奧術技藝感興趣的派系拉攏，例如豎琴手、龍之教團與紅袍法師。"},
{1: "當你達到「法術火法術」表中指定的術士等級時，你此後總是準備好所列的法術。"},
{1: "你獲得所有不具{@itemProperty 2H|XPHB|雙手}或{@itemProperty H|XPHB|重型}屬性之近戰軍用武器的熟練。你可以將一把你具有熟練的近戰武器作為你法師法術的{@variantrule Spellcasting Focus|XPHB}。",
 2: "你也從下列技能中選擇一項獲得熟練：{@skill Acrobatics|XPHB}、{@skill Athletics|XPHB}、{@skill Performance|XPHB}或{@skill Persuasion|XPHB}。"},
{1: "寒冬行者在冰風谷等荒涼冰封的荒野中磨練他們的技藝。這些冷酷、覆霜的遊俠獵殺出沒於極地荒原的怪物，最終自己也成為嚴寒的恐怖存在。寒冬行者熟知冰風谷的各種現象，包括殞落的耐瑟瑞爾城市中潛藏的魔法、{@creature yeti|XMM|雪人}與{@creature crag cat|SKT|峭壁貓}等當地特有的怪物，以及幽暗地域入侵者日益增長的威脅。由於他們冷酷的務實態度、可怕的魔法以及對該地區的精通，寒冬行者同時受到尊敬與畏懼。十鎮的居民說，寒冬行者經常接觸邪惡存在，因而獲得了他們可怕的力量。另一方面，許多雷格德游牧民族則相信，是自然之靈賜予了寒冬行者一種獨特的詛咒。"},
{1: "當你達到「寒冬行者法術」表中指定的遊俠等級時，你此後總是準備好所列的法術。"},
{1: "你總是準備好{@spell Counterspell|XPHB}。", 2: "此外，每當一個目標在對抗你施展的{@spell Counterspell|XPHB}的豁免檢定中失敗時，你恢復 {@dice 1d4} 點術法點。"},
{1: "你總是準備好{@spell Moonbeam|XPHB}法術。",
 2: "當你施展{@spell Moonbeam|XPHB}時，你可以修改該法術，使你在法術生效期間發出微弱的光芒。發光期間，你在 5 呎內發出{@variantrule Dim Light|XPHB}，且每當一個生物在對抗此月光束效果的豁免檢定中失敗時，你 60 呎內另一個你能看見、由你選擇的生物恢復 {@dice 2d4} {@variantrule Hit Points|XPHB}。",
 3: `一旦你使用此特性修改一次月光束的施展，在完成${LR}前無法再次使用。`},
{0: "額外攻擊", 1: "每當你在你的回合中採取{@action Attack|XPHB}動作時，你可以攻擊兩次，而非一次。此外，你可以用{@filter 一個施法時間為一個動作的法師戲法|spells|level=0|class=wizard|cast time=action}取代其中一次攻擊。"},
{1: "你獲得範圍 60 呎的{@variantrule telepathy|XPHB}。當你使用此{@variantrule telepathy|XPHB}時，你可以同時聯繫數量等同於你感知調整值的生物（最少一個）。",
 2: "此外，你獲得智力豁免檢定的熟練。若你已擁有此熟練，你改為獲得一項你所缺乏之屬性的豁免檢定熟練。"},
{1: "從下列傷害類型中選擇一種：強酸、寒冷、火焰、閃電或雷鳴。當你與你的盟友處於你的守護靈光中時，擁有該傷害類型的{@variantrule Resistance|XPHB}。",
 2: "在你的每個回合開始時，你可以將此特性影響的傷害類型改為其他所列選項之一（不需動作）。"},
{1: "你在嚴酷環境中求生的經驗，讓你除了強化自己之外也能強化你的盟友。作為一個{@action Magic|XPHB}動作，選擇數量等同於你感知調整值、你能看見的生物（最少一個）。每個被選擇的生物恢復等同於 {@dice 1d10} 加上你遊俠等級的{@variantrule Hit Points|XPHB}，並在 1 小時內，於避免或結束{@condition Frightened|XPHB}狀態的豁免檢定上具有{@variantrule Advantage|XPHB}。"},
{1: "當你使用群體恢復時，每名被選擇的盟友在{@variantrule D20 Test|XPHB|D20 檢定}上具有{@variantrule Advantage|XPHB}，直到你的下個回合開始。"},
{1: "你獲得下列{@classFeature Cunning Strike|Rogue|XPHB|5|XPHB}選項。",
 2: "恐嚇（消耗：{@dice 1d6}）", 3: "目標必須成功通過一次感知豁免檢定，否則陷入{@condition Frightened|XPHB}狀態 1 分鐘。當目標以此方式陷入恐懼時，你對目標的攻擊檢定具有{@variantrule Advantage|XPHB}。",
 4: "{@condition Frightened|XPHB}的目標在其每個回合結束時重複此豁免檢定，成功時結束自身的效果。"},
{1: `當你使用動作奔湧時，你可以選擇${EM(30)}範圍內的盟友，數量至多等同於你的魅力調整值（最少一名）。每名被選擇的盟友都可以立即採取一個${R}來使用下列其中一個選項。`,
 2: "攻擊", 3: "該盟友以武器或{@variantrule Unarmed Strike|XPHB}進行一次攻擊。",
 5: "該盟友移動至多其{@variantrule Speed|XPHB}的一半，且不會引發{@action Opportunity Attack|XPHB}。"},
{1: `當你在劍詠啟動期間受到傷害時，你可以採取一個${R}消耗一個法術欄位，並將所受傷害減少該法術欄位環階五倍的數值。`},
{1: `當一個生物以攻擊檢定命中你時，你可以採取一個${R}迫使該生物進行一次對抗你法術豁免 DC 的感知豁免檢定。豁免失敗時，目標陷入{@condition Stunned|XPHB}狀態，直到你的下個回合結束。當目標處於{@condition Stunned|XPHB}狀態時，其{@variantrule Speed|XPHB}降為 0 呎。`},
{1: "你散發出與死亡三神之一相關的邪惡力量。當你使用{@subclassFeature Bloodthirst|Rogue|XPHB|Scion of the Three|FRHoF|3|FRHoF}並傳送時，你離開的空間或你的目的地空間（由你選擇）10 呎內每個由你選擇的生物，受到等同於你智力調整值的傷害；傷害類型與你在恐怖效忠特性中所選擇而獲得的傷害{@variantrule Resistance|XPHB}相同。此特性造成的傷害無視{@variantrule Resistance|XPHB}。"},
{1: "你充盈著月亮的力量，以下列方式改善你的月之激勵。",
 2: "新月之影", 3: `當你使用激勵之蝕時，獲得吟遊詩人激勵骰的生物也可以陷入{@condition Invisible|XPHB}狀態，並立即採取一個${R}傳送至多 30 呎到一個它能看見的未佔據空間。該生物保持{@condition Invisible|XPHB}直到其下個回合開始。`,
 4: "滿月之輝", 5: "當你使用月之活力時，你可以擲 {@dice 1d6} 並使用擲出的數字，而不消耗吟遊詩人激勵骰。"},
{1: "你的{@subclassFeature Spellfire Burst|Sorcerer|XPHB|Spellfire|FRHoF|3|FRHoF}獲得改善。你將你的{@class Sorcerer|XPHB}等級加到從{@subclassFeature Bolstering Flames|Sorcerer|XPHB|Spellfire|FRHoF|3|FRHoF}獲得的{@variantrule Temporary Hit Points|XPHB}上，且{@subclassFeature Radiant Fire|Sorcerer|XPHB|Spellfire|FRHoF|3|FRHoF}的傷害增加為 {@dice 1d8}。"},
{},
{1: `當你被一次攻擊檢定命中時，你可以採取一個${R}將該攻擊對你造成的傷害減半（向下取整），並迫使攻擊者進行一次對抗你法術豁免 DC 的敏捷豁免檢定。豁免失敗時，攻擊者受到等同於 {@dice 2d10} 加上你魅力調整值的傷害，類型為下列其中一種（由你選擇）：強酸、寒冷、火焰、閃電或雷鳴。豁免成功時，攻擊者受到一半傷害。`},
{1: `當你施展{@spell Hunter's Mark|XPHB}時，你可以化為幽靈般的雪之形態。此形態持續到法術結束，處於此形態期間，你獲得下列好處。一旦你使用此特性，在完成${LR}前無法再次使用，除非你消耗一個 4 環以上的法術欄位（不需動作）。`,
 2: "冰凍之魂", 3: `你對寒冷傷害具有{@variantrule Immunity|XPHB}。當你首次化為此形態時，以及在你後續每個回合開始時，${EM(15)}範圍內每個由你選擇的生物受到 {@damage 2d4} 寒冷傷害。`,
 5: "你對{@condition Grappled|XPHB}、{@condition Prone|XPHB}與{@condition Restrained|XPHB}狀態具有{@variantrule Immunity|XPHB}。你可以穿過生物與物件，如同它們是{@variantrule Difficult Terrain|XPHB}，但若你在生物或物件內部結束你的回合，你會受到 {@damage 1d10} 力場傷害。若此形態在你位於生物或物件內部時結束，你會被推到最近的未佔據空間。"},
{1: `當一個你能看見、位於你 60 呎內的盟友在豁免檢定中失敗時，你可以採取一個${R}消耗一次不屈特性的使用次數。該盟友可以立即重擲該豁免檢定，並獲得等同於你戰士等級的加值；該盟友必須使用新的擲骰結果。`},
{1: `作為一個{@variantrule Bonus Action|XPHB}，你以魔法將你的心智延伸至未來。在 1 小時內，你在{@variantrule D20 Test|XPHB|D20 檢定}上具有{@variantrule Advantage|XPHB}。一旦你使用此特性，在完成${LR}前無法再次使用。你也可以消耗一個 6 環以上的法術欄位來恢復此特性的使用次數（不需動作）。`},
{2: "割喉者", 3: "當你完成{@variantrule Short Rest|XPHB}時，你恢復一次已消耗的{@subclassFeature Bloodthirst|Rogue|XPHB|Scion of the Three|FRHoF|3|FRHoF}使用次數。",
 4: "殺意", 5: "當你擲{@classFeature Sneak Attack|Rogue|XPHB|1|XPHB}傷害時，你可以將骰子上擲出的 1 或 2 視為 3。"},
{2: `當你使用{@classFeature Innate Sorcery|Sorcerer|XPHB|1}時，你可以改變它，為自己灌注法術火的精華，在此次天生術法啟動期間獲得下列好處。一旦你使用此特性改變天生術法，在完成${LR}前無法再次使用，除非你花費 5 點術法點（不需動作）來恢復其使用次數。`,
 3: "燃燒生命力", 4: "每回合一次，當你被一次攻擊檢定命中時，你可以消耗若干{@variantrule Hit Point Dice|XPHB}，數量至多等同於你的魅力調整值（最少一顆）。擲出所消耗的骰子，並將該攻擊的傷害減少擲骰總和。",
 6: "你獲得 60 呎的{@variantrule Fly Speed|XPHB}，並可以懸浮。",
 7: "法術閃避", 8: "當你受到一個允許你進行豁免檢定以只受一半傷害的法術或魔法效果影響時，若你豁免成功，你改為不受傷害，若失敗則只受一半傷害。若你陷入{@condition Incapacitated|XPHB}狀態，你無法使用此好處。"},
{2: "強化集結", 3: `群體恢復與集結奔湧的效果範圍現在都變為${EM(60)}範圍。`,
 4: "不動搖的勇氣", 5: "你對{@condition Charmed|XPHB}與{@condition Frightened|XPHB}狀態具有{@variantrule Immunity|XPHB}。"},
{3: "你擁有 60 呎的{@variantrule Fly Speed|XPHB}，並可以懸浮。",
 4: "小願望", 5: `當你或你{@classFeature Aura of Protection|Paladin|XPHB|6|XPHB}中的一名盟友在{@variantrule D20 Test|XPHB}中失敗時，你可以採取一個${R}使該{@variantrule D20 Test|XPHB}改為成功。`},
], D);
