export const LR = "{@variantrule Long Rest|XPHB}";
export const BA = "{@variantrule Bonus Action|XPHB}";
export const D = {"Banneret": "旗手", "Bladesinger": "劍詠者", "Bladesong": "劍詠", "Bolstering Flames": "鼓舞之焰", "College of the Moon": "月亮學院",
 "Dao's Crush": "達歐碾壓", "Djinni's Escape": "燈神脫逃", "Dread Allegiance": "恐怖效忠", "Efreeti's Fury": "伊夫利特之怒", "Elemental Smite": "元素斬擊",
 "Frigid Explorer": "嚴寒探險家", "Genie's Splendor": "精靈的輝煌", "Group Recovery": "群體恢復", "Hunter's Rime": "獵人之霜", "Knightly Envoy": "騎士使節",
 "Marid's Surge": "馬利德湧浪", "Mind Magic": "心靈魔法", "Moon's Inspiration": "月之激勵", "Oath of the Noble Genies": "貴族精靈之誓", "Primal Lore": "原初知識",
 "Radiant Fire": "光輝之火", "Scion of the Three": "三神後裔", "Spellfire Burst": "法術火爆發", "God": "神祇"};
export const M1 = [
{1: "旗手是英勇與領導的典範，他們保護無辜者，並號召冒險者同伴為正義與自由的志業而戰。許多旗手是效力於寇米爾、銀色邊境、達瑪拉、切森塔或費倫其他土地的騎士。他們以遊俠騎士的身分漫遊諸國，將對抗邪惡的戰鬥延伸到其王國邊境之外。",
 2: "旗手依靠判斷、勇氣與對騎士精神準則的忠誠，引導自己擊敗惡徒。一名獨行的旗手是一名技藝高超的戰士，但當率領一群盟友時，這些戰士中的一員即使是裝備低劣的民兵，也能將其轉變為兇猛的戰團。"},
{1: "劍詠者精通一種融合劍術與舞蹈的法師傳統。在戰鬥中，劍詠者運用繁複而優雅的動作抵擋傷害，並讓劍詠者得以將魔法引導至毀滅性的攻擊與巧妙的防禦之中。許多見過劍詠者施展身手的人，都將那場表演視為一生中最美麗的經歷之一——一場伴隨著歌唱之劍的輝煌舞蹈。",
 2: "劍詠與最早精通此技藝並創造此名稱的古老精靈社會息息相關。直到今日，大多數劍詠者仍來自古老的精靈國度，例如密斯卓諾，或是與精靈共享土地與歷史的非精靈社會，例如銀色邊境。無論來自何方，劍詠者都將他們的天賦帶往國度各地，幫助平民並完成英勇事蹟。大多數社群都將劍詠者的到來視為好兆頭。"},
{1: `作為一個${BA}，只要你沒有穿著護甲或使用盾牌，你就可以喚起一種名為劍詠的精靈魔法。`,
 2: "劍詠持續 1 分鐘，若你陷入{@condition Incapacitated|XPHB}狀態、穿上護甲或盾牌，或使用雙手以武器進行攻擊，它會提早結束。你可以隨時解除劍詠（不需動作）。",
 3: `劍詠啟動期間，你獲得下列好處。你可以喚起劍詠的次數等同於你的智力調整值（最少一次），並在完成${LR}時恢復所有已消耗的使用次數。當你使用奧術回復時，你恢復一次已消耗的使用次數。`,
 4: "敏捷", 5: "你的 AC 獲得等同於你智力調整值的加值（最少 +1），且你的{@variantrule Speed|XPHB}增加 10 呎。此外，你在敏捷（{@skill Acrobatics|XPHB}）檢定上具有{@variantrule Advantage|XPHB}。",
 6: "劍技", 7: "每當你以你具有熟練的武器進行攻擊時，你可以在攻擊與傷害擲骰上使用你的智力調整值，而非力量或敏捷。",
 8: "專注", 9: "當你為了維持{@status Concentration|XPHB}而進行體質豁免檢定時，你可以將你的智力調整值加到總值上。"},
{0: "嗜血", 1: `當一個你能看見、位於你 30 呎內的敵人受到傷害，且在受到該傷害後處於{@status Bloodied|XPHB}狀態但未被直接殺死時，你可以採取一個{@variantrule Reaction|XPHB}並{@variantrule Teleportation|XPHB|傳送}到該敵人 5 呎內一個你能看見的未佔據空間。接著你可以進行一次近戰攻擊。你可以使用此特性的次數等同於你的智力調整值（最少一次），並在完成${LR}時恢復所有已消耗的使用次數。`},
{1: "你或你 30 呎內一個你能看見的生物，獲得等同於 {@dice 1d4} 加上你魅力調整值的{@variantrule Temporary Hit Points|XPHB}。"},
{1: "月亮學院的起源可追溯至月之海群島的古老德魯伊結社，他們委託此傳統的第一批吟遊詩人記錄群島及其人民的故事。此學院的吟遊詩人汲取群島的妖精魔法與月井的原初之力，來鼓舞盟友、保護自然世界，並激發他們的吟遊詩人創作。"},
{2: "大地在你神聖斬擊的目標周圍隆起。目標陷入{@condition Grappled|XPHB}狀態（脫逃 DC 等於你的法術豁免 DC）。處於{@condition Grappled|XPHB}狀態時，目標陷入{@condition Restrained|XPHB}狀態。"},
{2: "你{@variantrule Teleportation|XPHB|傳送}到你 30 呎內一個你能看見的未佔據空間，並化為半虛體的形態，持續到你的下個回合結束。處於此形態時，你擁有鈍擊、穿刺與劈砍傷害的{@variantrule Resistance|XPHB}，並對{@condition Grappled|XPHB}、{@condition Prone|XPHB}與{@condition Restrained|XPHB}狀態具有{@variantrule Immunity|XPHB}。"},
{1: `選擇死亡三神之一：{@deity Bane|Faerûnian|FRHoF}、{@deity Bhaal|Faerûnian|FRHoF}或{@deity Myrkul|Faerûnian|FRHoF}。你獲得一種傷害類型的{@variantrule Resistance|XPHB}，以及施展一個戲法的能力，詳見下表；智力是你施展此戲法的施法屬性。當你完成${LR}時，你可以改變你的選擇。`},
{2: "你神聖斬擊的目標受到額外 {@damage 2d4} 火焰傷害，且火焰從目標跳到你 30 呎內另一個你能看見的生物身上。第二個生物也受到 {@damage 2d4} 火焰傷害。"},
{1: "在你施展{@spell Divine Smite|XPHB}後，你可以立即消耗一次{@classFeature Channel Divinity|Paladin|XPHB|3|XPHB}的使用次數，並喚起下列其中一種效果。"},
{2: "刺骨嚴寒", 3: "你的武器攻擊、遊俠法術與遊俠特性造成的傷害無視寒冷傷害的{@variantrule Resistance|XPHB}。",
 4: "抗寒", 6: "極地打擊", 7: "當你以武器進行攻擊檢定命中一個生物時，你可以對目標造成額外 {@damage 1d4} 寒冷傷害，目標每回合只能受到此額外傷害一次。當你達到遊俠 11 級時，此額外傷害增加為 {@dice 1d6}。"},
{1: "當你達到「精靈法術」表中指定的聖騎士等級時，你此後總是準備好所列的法術。"},
{1: "當你沒有穿著任何護甲時，你的基礎{@variantrule Armor Class|XPHB}等於 10 加上你的敏捷與魅力調整值。你可以使用盾牌並仍獲得此好處。",
 2: "你也從下列技能中選擇一項獲得熟練：{@skill Acrobatics|XPHB}、{@skill Intimidation|XPHB}、{@skill Performance|XPHB}或{@skill Persuasion|XPHB}。"},
{1: "當你使用回氣恢復{@variantrule Hit Points|XPHB}時，你可以選擇源自你的 30 呎{@variantrule Emanation [Area of Effect]|XPHB|發散}範圍內的盟友，數量至多等同於你的魅力調整值（最少一名）。每名被選擇的盟友恢復等同於 {@dice 1d4} 加上你戰士等級的{@variantrule Hit Points|XPHB}。一旦你使用此能力，在完成{@variantrule Short Rest|XPHB|短休}或{@variantrule Long Rest|XPHB}前無法再次使用。"},
{1: "冰霜覆蓋你與你的獵物，保護你並使牠們遲緩。當你施展{@spell Hunter's Mark|XPHB}時，你獲得等同於 {@dice 1d10} 加上你{@class Ranger|XPHB}等級的{@variantrule Temporary Hit Points|XPHB}。",
 2: "此外，當一個生物被你的{@spell Hunter's Mark|XPHB}標記時，它無法採取{@action Disengage|XPHB}動作。"},
{1: "你懂得如何以高貴大使的身分優雅地舉止。你獲得下列好處。",
 2: "理解", 3: "你可以施展{@spell Comprehend Languages|XPHB}法術，但只能作為{@variantrule Ritual|XPHB}施展。魅力是你施展此法術的施法屬性。",
 4: "通曉多語", 5: `你從《玩家手冊》或本書第 2 章的語言表中學會一種語言。當你完成${LR}時，你可以將從此好處學會的語言，替換為你在過去 24 小時內聽過、看過其手語或讀過的另一種語言。`,
 6: "能言善道", 7: "你從下列技能中選擇一項獲得熟練：{@skill Insight|XPHB}、{@skill Intimidation|XPHB}、{@skill Persuasion|XPHB}或{@skill Performance|XPHB}。"},
{1: "知識領域重視學習與理解勝過一切。汲取此領域力量的牧師研讀深奧的知識、收集古老的典籍、探索秘密之地，並審視心智的運作。對他們而言，知識比物質財富更有價值，而學習是一種崇拜的行為。圖書館、大學與其他教育機構也汲取知識領域的力量。",
 2: "知識之神從奧術魔法的大師到工藝與發明的守護者都有。在費倫，知識領域的牧師崇拜學識與巧思之神，例如{@deity Oghma|Faerûnian|FRHoF}與{@deity Gond|Faerûnian|FRHoF}，以及許多其他神祇。"},
{0: "知識領域法術", 1: "當你達到「知識領域法術」表中指定的牧師等級時，你此後總是準備好所列的法術。",
 4: "{@spell Command|XPHB}、{@spell Comprehend Languages|XPHB}*、{@spell Detect Magic|XPHB}*、{@spell Detect Thoughts|XPHB}*、{@spell Identify|XPHB}*、{@spell Mind Spike|XPHB}*",
 5: "{@spell Dispel Magic|XPHB}、{@spell Nondetection|XPHB}、{@spell Tongues|XPHB}*",
 6: "{@spell Arcane Eye|XPHB}*、{@spell Banishment|XPHB}、{@spell Confusion|XPHB}",
 7: "{@spell Legend Lore|XPHB}*、{@spell Scrying|XPHB}*、{@spell Synaptic Static|XPHB}",
 8: "*預言系法術"},
{2: "你神聖斬擊的目標，以及源自你的 10 呎{@variantrule Emanation [Area of Effect]|XPHB|發散}範圍內每個由你選擇的生物，都要進行一次對抗你法術豁免 DC 的力量豁免檢定。豁免失敗時，生物被直直推離你 15 呎，並陷入{@condition Prone|XPHB}狀態。"},
{2: "作為一個{@action Magic|XPHB}動作，你可以消耗一次引導神力的使用次數來顯現你的魔法知識。選擇一個你已準備、位於「知識領域法術」表上的預言系法術。作為該動作的一部分，你施展該法術，不需消耗法術欄位，也不需要材料成分。"},
{1: "月亮原初且永恆變幻的力量流經你，給予你下列好處。",
 2: "激勵之蝕", 3: `當你採取一個${BA}給予一個生物吟遊詩人激勵骰時，作為該${BA}的一部分，你可以陷入{@condition Invisible|XPHB}狀態，並傳送至多 30 呎到一個你能看見的未佔據空間。此隱形持續到你的下個回合開始，並在你進行攻擊檢定、造成傷害或施展法術後立即提早結束。`,
 4: "月之活力", 5: "每回合一次，當你以法術為一個生物恢復{@variantrule Hit Points|XPHB}時，你可以消耗一顆吟遊詩人激勵骰，將恢復的{@variantrule Hit Points|XPHB}增加等同於擲出該吟遊詩人激勵骰的數值。該生物的{@variantrule Speed|XPHB}也增加 10 呎，直到其下個回合結束。"},
{1: "立下貴族精靈之誓的聖騎士崇敬元素位面的力量。透過立下此誓言，聖騎士從四種不同的精靈汲取力量——大地之主達歐、風之主燈神、火之主伊夫利特，以及水之主馬利德。在費倫，許多立下此誓言的聖騎士來自卡林姍——一片精靈充斥的土地。",
 2: "立下此誓言的聖騎士經常承擔帶領他們走遍國度各地、跨越多元宇宙——包括元素位面——的任務。這些聖騎士共享下列信條：",
 3: "在毀滅的灰燼中播下創造的種子。", 4: "以輝煌與優雅領導。", 5: "尊重元素，並敬畏它們的怒火。"},
{1: "你學會德魯伊語，以及一個來自德魯伊法術列表的戲法。它對你而言視為吟遊詩人法術，但不計入你已知的戲法數量。每當你提升一個吟遊詩人等級時，你可以將此戲法替換為另一個由你選擇、來自德魯伊法術列表的戲法。",
 2: "此外，從下列技能中選擇一項：{@skill Animal Handling|XPHB}、{@skill Insight|XPHB}、{@skill Medicine|XPHB}、{@skill Nature|XPHB}、{@skill Perception|XPHB}或{@skill Survival|XPHB}。你獲得該技能的熟練。"},
{1: "你 30 呎內一個你能看見的生物受到 {@damage 1d4} 火焰或光耀傷害（由你選擇）。"},
{1: "三神後裔從一群被稱為死亡三神的邪惡神祇汲取力量：暴政之神{@deity Bane|Faerûnian|FRHoF}、暴力與謀殺之神{@deity Bhaal|Faerûnian|FRHoF}，以及死亡之神{@deity Myrkul|Faerûnian|FRHoF}。雖然此子職業的一些盜賊熱切地向這三位陰森的神祇宣誓效忠，但另一些人則是因詛咒而被推上這條道路。無論如何，後裔的力量會以各種神秘天賦的形式顯現，並伴隨著打擊敵人、令敵人恐懼的不可思議天賦。",
 2: "三神後裔在博德之門最為常見，死亡三神長久以來一直在那裡爭奪對凡人之心的影響力。{@deity Bane|Faerûnian|FRHoF}、{@deity Bhaal|Faerûnian|FRHoF}與{@deity Myrkul|Faerûnian|FRHoF}的地下教團，經常將三神後裔視為他們最有用的特工之一。在博德之門以外，世俗的盜賊公會，例如安姆的影賊或深水城的贊納薩公會，可能會謹慎地請一名三神後裔承接特別暴力的委託。"},
{1: `當你在你的回合中，作為{@action Magic|XPHB}動作或${BA}的一部分花費至少 1 點術法點時，你可以釋放下列其中一種由你選擇的魔法效果。你每回合只能這樣做一次。`},
];
