// EGW 覺醒／昇華物品 _copy._mod 的文字
import add from "../_addex.mjs";
const RS = (w, st, v = "獲得以下屬性") => `當這把${w}進入${st}狀態時，它${v}：`;
add({
"When the dagger reaches an awakened state, it gains the following properties:": RS("匕首", "覺醒"),
"The weapon's bonus to attack and damage rolls increases to +2.": "武器的攻擊檢定與傷害擲骰加值提升至 +2。",
"While holding the weapon, you can use an action to cast one of the following spells from it (save {@dc 15}): {@spell fabricate}, {@spell hallucinatory terrain}, {@spell major image}, or {@spell phantasmal killer}. Once a spell has been cast using the dagger, that spell can't be cast from the dagger again until the next dawn.": "持握武器時，你可以使用一個動作從它施展以下法術之一（豁免 {@dc 15}）：{@spell fabricate}、{@spell hallucinatory terrain}、{@spell major image}或{@spell phantasmal killer}。以匕首施展過某道法術後，在下一個黎明之前無法再從匕首施展該法術。",
"When the dagger reaches an exalted state, it gains the following properties:": RS("匕首", "昇華"),
"The weapon's bonus to attack and damage rolls increases to +3.": "武器的攻擊檢定與傷害擲骰加值提升至 +3。",
"The saving throw DC for spells cast from the dagger increases to 17.": "從匕首施展之法術的豁免 DC 提升至 17。",
"While holding the dagger, you can turn {@condition invisible} as an action. Anything you are wearing or carrying is {@condition invisible} with you. You remain {@condition invisible} until you stop holding the dagger, until you attack or cast a spell that forces a creature to make a saving throw, or until you use a bonus action to become visible again.": "持握匕首時，你可以使用一個動作變為{@condition invisible}。你穿戴或攜帶的任何物品都會與你一同{@condition invisible}。你會保持{@condition invisible}，直到你不再持握匕首、直到你攻擊或施展迫使生物進行豁免檢定的法術，或直到你使用一個附贈動作重新現形為止。",
"When Danoth's Visor reaches an awakened state, it gains the following properties:": "當達諾斯的護目鏡進入覺醒狀態時，它獲得以下屬性：",
"You see {@condition invisible} creatures and objects within 60 feet of you as if they were visible, and you can see into the Ethereal Plane. Ethereal creatures and objects appear ghostly and translucent.": "你能看見你 60 呎內{@condition invisible}的生物與物體，如同它們是可見的，且你能看進乙太位面。乙太位面的生物與物體看起來如幽魂般半透明。",
"As a bonus action, you can speak a command word and use the goggles to see into and through solid matter. This vision has a radius of 60 feet and lasts for 1 minute. To you, solid objects within that radius appear transparent. The vision can penetrate 1 foot of stone, 1 inch of common metal, or up to 3 feet of wood or dirt. Thicker substances block the vision, as does a thin sheet of lead. This property can't be used again until the next dawn.": "作為一個附贈動作，你可以說出命令語，使用護目鏡看進並看穿固體物質。這種視覺的半徑為 60 呎，持續 1 分鐘。對你而言，該半徑內的固體物體看起來是透明的。這種視覺可以穿透 1 呎的石頭、1 吋的普通金屬，或至多 3 呎的木頭或泥土。更厚的物質會阻擋視線，薄薄一層鉛也會。此屬性在下一個黎明之前無法再次使用。",
"As a bonus action, you can speak a command word to switch the goggles into spyglass mode. While in this mode, creatures and objects viewed through the goggles are magnified to twice their size. Speaking the command word again reverts the goggles to their normal operation.": "作為一個附贈動作，你可以說出命令語，將護目鏡切換為望遠鏡模式。在此模式下，透過護目鏡觀看的生物與物體會放大為原本的兩倍大小。再次說出命令語會讓護目鏡恢復正常運作。",
"When Danoth's Visor reaches an exalted state, it gains the following properties:": "當達諾斯的護目鏡進入昇華狀態時，它獲得以下屬性：",
"You automatically detect illusions you can see and automatically succeed on saving throws against them. In addition, you see a bright aura around any creature that isn't in its true form.": "你會自動察覺你能看見的幻術，並自動通過對抗它們的豁免檢定。此外，你會看見任何並非處於真實形態的生物周圍有一圈明亮的靈光。",
"As an action, you can cast the {@spell antimagic field} spell from the visor. This property can't be used again until the next dawn.": "作為一個動作，你可以從護目鏡施展{@spell antimagic field}法術。此屬性在下一個黎明之前無法再次使用。",
"When the Grimoire Infinitus reaches an awakened state, it gains the following properties:": "當無盡魔典進入覺醒狀態時，它獲得以下屬性：",
"While you carry the spellbook, you have advantage on saving throws against spells and magical effects.": "攜帶這本法術書時，你在對抗法術與魔法效果的豁免檢定上具有優勢。",
"When you prepare wizard spells using the grimoire as your spellbook, the number of spells you can prepare increases by 1 again.": "當你以這本魔典作為你的法術書準備法師法術時，你可準備的法術數量再增加 1。",
"When the Grimoire Infinitus reaches an exalted state, it gains the following properties:": "當無盡魔典進入昇華狀態時，它獲得以下屬性：",
"You can now use your Arcane Recovery feature twice between long rests, rather than once.": "你現在可以在兩次長休之間使用你的奧術回復特性兩次，而非一次。",
"When the warhammer reaches an awakened state, it gains the following properties:": RS("戰錘", "覺醒"),
"You gain a burrowing speed equal to your walking speed. You can use your burrowing speed to move through sand, loose earth, mud, or ice, not solid rock.": "你獲得等同於你步行速度的掘穴速度。你可以使用掘穴速度穿過沙地、鬆土、泥巴或冰，但無法穿過堅硬的岩石。",
"When a creature you can see within 30 feet of you hits you with an attack while you are wielding the warhammer, you can use your reaction to deal an amount of psychic damage to that creature equal to the damage you took from the attack. This property can't be used again until the next dawn.": "當你持用戰錘時，若你 30 呎內一個你能看見的生物以攻擊命中你，你可以使用你的反應對該生物造成心靈傷害，數值等於你從該次攻擊受到的傷害。此屬性在下一個黎明之前無法再次使用。",
"When the warhammer reaches an exalted state, it gains the following properties:": RS("戰錘", "昇華"),
"When you have fewer hit points than half your hit point maximum, the warhammer deals an extra {@damage 2d6} bludgeoning damage on a hit. You can burrow through solid rock at half your burrowing speed and leave a 5-foot-diameter tunnel in your wake.": "當你的生命值低於生命值上限的一半時，戰錘命中時額外造成 {@damage 2d6} 點鈍擊傷害。你可以用掘穴速度的一半掘穿堅硬的岩石，並在身後留下一條直徑 5 呎的隧道。",
"As an action, you can use the warhammer to cast one of the following spells from it (save {@dc 17}): {@spell earthquake}, {@spell meld into stone}, or {@spell stone shape}. Once a spell has been cast using the warhammer, that spell can't be cast from the warhammer again until the next dawn.": "作為一個動作，你可以使用戰錘從它施展以下法術之一（豁免 {@dc 17}）：{@spell earthquake}、{@spell meld into stone}或{@spell stone shape}。以戰錘施展過某道法術後，在下一個黎明之前無法再從戰錘施展該法術。",
"When the armor reaches an awakened state, it gains the following properties:": "當這件護甲進入覺醒狀態時，它獲得以下屬性：",
"The AC bonus of the armor increases to +2.": "護甲的 AC 加值提升至 +2。",
"While you are transformed by an effect that replaces any of your game statistics with those of another creature, your bonus to melee attack and damage rolls increases by 1 (to +2).": "當你被一個以另一生物的數據取代你任何遊戲數據的效果變形時，你的近戰攻擊檢定與傷害擲骰加值增加 1（變為 +2）。",
"When you cast the {@spell polymorph} spell using this armor, you can transform into a {@creature cave bear}.": "當你使用這件護甲施展{@spell polymorph}法術時，你可以變形為一隻{@creature cave bear}。",
"When the armor reaches an exalted state, it gains the following properties:": "當這件護甲進入昇華狀態時，它獲得以下屬性：",
"The AC bonus of the armor increases to +3.": "護甲的 AC 加值提升至 +3。",
"While you are transformed by an effect that replaces any of your game statistics with those of another creature, your bonus to melee attack and damage rolls increases by 1 (to +3).": "當你被一個以另一生物的數據取代你任何遊戲數據的效果變形時，你的近戰攻擊檢定與傷害擲骰加值增加 1（變為 +3）。",
"When you cast the {@spell polymorph} spell using this armor, you can transform into a {@creature guardian wolf|EGW}.": "當你使用這件護甲施展{@spell polymorph}法術時，你可以變形為一隻{@creature guardian wolf|EGW}。",
"When the Infiltrator's Key reaches an awakened state, it gains the following properties:": "當滲透者之鑰進入覺醒狀態時，它獲得以下屬性：",
"While holding the key, you can use a bonus action to transform the key into a magic dagger or back into a key. While the key is in the form of a dagger, you gain a +1 bonus to attack and damage rolls made with it, and it returns to your hand immediately after it is used to make a ranged attack.": "持握鑰匙時，你可以使用一個附贈動作將鑰匙變為一把魔法匕首，或變回鑰匙。當鑰匙處於匕首形態時，你以它進行的攻擊檢定與傷害擲骰獲得 +1 加值，且它被用來進行遠程攻擊後會立刻回到你手中。",
"While holding the key, you can use an action to cast one of the following spells from it: {@spell alter self}, {@spell invisibility}, {@spell knock}, or {@spell pass without trace}. Once a spell has been cast using the key, it can't be used to cast that spell again until the next dawn.": "持握鑰匙時，你可以使用一個動作從它施展以下法術之一：{@spell alter self}、{@spell invisibility}、{@spell knock}或{@spell pass without trace}。以鑰匙施展過某道法術後，在下一個黎明之前無法再用它施展該法術。",
"When the Infiltrator's Key reaches an exalted state, it gains the following properties:": "當滲透者之鑰進入昇華狀態時，它獲得以下屬性：",
"As a bonus action, you can touch the key to a floor, wall, or ceiling that is no more than 5 feet thick and cause a magical opening to appear in the surface. When you create the opening, you choose its length and width, up to 10 feet for each dimension. The opening lasts until the key passes through it to the other side, at which point it disappears (if a creature is in the opening when the doorway closes, the creature is safely shunted to the nearest unoccupied space). The key can't be used to create another opening until the next dawn.": "作為一個附贈動作，你可以用鑰匙觸碰厚度不超過 5 呎的地板、牆壁或天花板，使表面出現一個魔法開口。建立開口時，你選擇它的長度與寬度，每個維度至多 10 呎。開口持續到鑰匙穿過它到達另一側為止，此時開口消失（若門道關閉時有生物位於開口中，該生物會被安全地推到最近的未被佔據空間）。在下一個黎明之前，鑰匙無法再用來建立另一個開口。",
"While holding the key, you can use an action to cast one of the following spells from it: {@spell dimension door}, {@spell gaseous form}, or {@spell mislead}. Once a spell has been cast using the key, it can't be used to cast that spell again until the next dawn.": "持握鑰匙時，你可以使用一個動作從它施展以下法術之一：{@spell dimension door}、{@spell gaseous form}或{@spell mislead}。以鑰匙施展過某道法術後，在下一個黎明之前無法再用它施展該法術。",
"When the whip reaches an awakened state, it gains the following properties:": RS("鞭子", "覺醒"),
"The saving throw DC for the weapon's poisons increases to 15.": "武器毒素的豁免 DC 提升至 15。",
"The weapon gains a new poison option called Ghoul's Blood. A creature that fails the saving throw against this poison is {@condition poisoned} for 1 minute. While {@condition poisoned} in this way, the creature is {@condition paralyzed}. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.": "武器獲得一種名為食屍鬼之血的新毒素選項。對此毒素豁免失敗的生物會{@condition poisoned} 1 分鐘。以此方式{@condition poisoned}時，該生物處於{@condition paralyzed}狀態。該生物可以在它每個回合結束時重複豁免檢定，成功時結束自身的效果。",
"When the whip reaches an exalted state, it gains the following additional properties:": "當這把鞭子進入昇華狀態時，它額外獲得以下屬性：",
"The saving throw DC for the weapon's poisons increases to 17.": "武器毒素的豁免 DC 提升至 17。",
"The weapon gains a new poison option called Cockatrice Tears. A creature that fails the saving throw against this poison begins to turn to stone and is {@condition restrained}. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is {@condition petrified} for 24 hours.": "武器獲得一種名為雞蛇之淚的新毒素選項。對此毒素豁免失敗的生物開始石化，並處於{@condition restrained}狀態。它必須在它下個回合結束時重複豁免檢定。成功時效果結束。失敗時，該生物{@condition petrified} 24 小時。",
"When the mace reaches an awakened state, it gains the following properties:": RS("硬頭錘", "覺醒"),
"The weapon's bonus to attack and damage rolls increases to +2, and the extra fire damage dealt by the weapon when it is ignited increases to {@dice 2d6}.": "武器的攻擊檢定與傷害擲骰加值提升至 +2，且武器燃燒時造成的額外火焰傷害提升至 {@dice 2d6}。",
"The weapon's Summon Devil feature can also be used to summon a {@creature bearded devil}.": "武器的召喚魔鬼特性也可以用來召喚一隻{@creature bearded devil}。",
"You have resistance to poison damage while holding this weapon.": "持握這把武器時，你具有毒素傷害抗性。",
"When the mace reaches an exalted state, it gains the following properties:": RS("硬頭錘", "昇華"),
"The weapon's bonus to attack and damage rolls increases to +3, and the extra fire damage dealt by the weapon when it is ignited increases to {@dice 3d6}. Fire damage dealt by the mace ignores resistance to fire damage.": "武器的攻擊檢定與傷害擲骰加值提升至 +3，且武器燃燒時造成的額外火焰傷害提升至 {@dice 3d6}。硬頭錘造成的火焰傷害無視火焰傷害抗性。",
"The weapon's Summon Devil feature can also be used to summon a {@creature barbed devil}.": "武器的召喚魔鬼特性也可以用來召喚一隻{@creature barbed devil}。",
"You have resistance to fire damage while you hold this weapon.": "持握這把武器時，你具有火焰傷害抗性。",
"When the spear reaches an awakened state, it gains the following properties:": RS("矛", "覺醒"),
"The weapon's bonus to attack and damage rolls increases to +2, and the extra piercing damage dealt by the weapon increases to {@damage 2d8}.": "武器的攻擊檢定與傷害擲骰加值提升至 +2，且武器造成的額外穿刺傷害提升至 {@damage 2d8}。",
"When you hurl the spear and speak a command word, it transforms into a bolt of lightning, forming a line 5 feet wide that extends out from you to a creature you can see within 120 feet of you. Each creature in the line, excluding you, must make a {@dc 15} Dexterity saving throw, taking {@damage 8d6} lightning damage on a failed save, or half as much damage on a successful one. Ruin's Wake then returns to your hand. This property can't be used again until the next dawn.": "當你擲出這支矛並說出命令語時，它會化為一道閃電，形成一條寬 5 呎的線，從你延伸到你 120 呎內一個你能看見的生物。線上除了你以外的每個生物都必須進行一次 {@dc 15} 敏捷豁免檢定，失敗時受到 {@damage 8d6} 點閃電傷害，成功時傷害減半。毀滅餘波接著回到你手中。此屬性在下一個黎明之前無法再次使用。",
"When the spear reaches an exalted state, it gains the following properties:": RS("矛", "昇華"),
"While holding the spear, you can let out a battle cry as a bonus action. Each creature you choose within 30 feet of you gains advantage on attack rolls until the start of your next turn. This property can't be used again until the next dawn.": "持握這支矛時，你可以使用一個附贈動作發出戰吼。你 30 呎內每個你選擇的生物在你下個回合開始前的攻擊檢定具有優勢。此屬性在下一個黎明之前無法再次使用。",
"When you reduce a creature to 0 hit points with an attack from the spear, you can regain hit points equal to the damage you dealt with the attack. This property can't be used again until the next dawn.": "當你以這支矛的攻擊將一個生物的生命值降至 0 時，你可以恢復等同於該次攻擊所造成傷害的生命值。此屬性在下一個黎明之前無法再次使用。",
"The rapier grants the following benefits in its awakened state:": "這把刺劍在覺醒狀態下賦予以下益處：",
"The saving throw DC for the weapon's poison increases to 15.": "武器毒素的豁免 DC 提升至 15。",
"While holding the rapier, you can use an action to cast one of the following spells from it (save {@dc 15}): {@spell cloudkill}, {@spell darkness}, {@spell levitate}, or {@spell web}. Once a spell has been cast using the rapier, that spell can't be cast from the rapier again until the next dawn.": "持握刺劍時，你可以使用一個動作從它施展以下法術之一（豁免 {@dc 15}）：{@spell cloudkill}、{@spell darkness}、{@spell levitate}或{@spell web}。以刺劍施展過某道法術後，在下一個黎明之前無法再從刺劍施展該法術。",
"The rapier grants the following benefits in its exalted state:": "這把刺劍在昇華狀態下賦予以下益處：",
"The saving throw DC for the weapon's poison and spells cast from the weapon increases to 17.": "武器毒素與從武器施展之法術的豁免 DC 提升至 17。",
"Magical darkness doesn't impede your {@sense darkvision}.": "魔法黑暗不會妨礙你的{@sense darkvision}。",
"While holding the weapon in dim light or darkness, you can use a bonus action to teleport up to 60 feet to an unoccupied space you can see that is also in dim light or darkness. This property can't be used again until the next dawn.": "在微光或黑暗中持握這把武器時，你可以使用一個附贈動作，傳送至多 60 呎到一個你能看見、同樣處於微光或黑暗中的未被佔據空間。此屬性在下一個黎明之前無法再次使用。",
"While wearing the Stormgirdle in its awakened state, you gain the following benefits:": "在覺醒狀態下繫著風暴腰帶時，你獲得以下益處：",
"Your Strength score becomes 23 if it isn't already 23 or higher.": "若你的力量值不到 23，它會變為 23。",
"Your Storm Avatar's lightning strike deals {@damage 4d6} lightning damage (instead of {@dice 3d6}).": "你的風暴化身的閃電打擊造成 {@damage 4d6} 點閃電傷害（而非 {@dice 3d6}）。",
"While transformed into a Storm Avatar, you gain a flying speed of 30 feet and can hover.": "化身為風暴化身時，你獲得 30 呎的飛行速度，並可以懸浮。",
"While wearing the Stormgirdle in its exalted state, you gain the following benefits:": "在昇華狀態下繫著風暴腰帶時，你獲得以下益處：",
"Your Strength score becomes 25 if it isn't already 25 or higher.": "若你的力量值不到 25，它會變為 25。",
"Your Storm Avatar's lightning strike deals {@damage 5d6} lightning damage (instead of {@dice 3d6}).": "你的風暴化身的閃電打擊造成 {@damage 5d6} 點閃電傷害（而非 {@dice 3d6}）。",
"You can cast the {@spell control weather} spell from the girdle. This property can't be used again until the next dawn.": "你可以從腰帶施展{@spell control weather}法術。此屬性在下一個黎明之前無法再次使用。",
"When the morningstar reaches an awakened state, it gains the following properties:": RS("釘頭錘", "覺醒"),
"The saving throw DC for spells cast from the morningstar increases to 15.": "從釘頭錘施展之法術的豁免 DC 提升至 15。",
"When you reduce a creature to 0 hit points with an attack using The Bloody End, you can cause the following effect: each creature of your choice within 15 feet of you must succeed on a {@dc 15} Wisdom saving throw or be {@condition frightened} of you until the end of your next turn. This property can't be used again until the next dawn.": "當你以血腥終結的攻擊將一個生物的生命值降至 0 時，你可以造成以下效果：你 15 呎內每個你選擇的生物都必須成功通過一次 {@dc 15} 感知豁免檢定，否則在你下個回合結束前對你{@condition frightened}。此屬性在下一個黎明之前無法再次使用。",
"When a creature hits you with a melee attack, you can use your reaction to deal {@damage 1d6} psychic damage to the attacker.": "當一個生物以近戰攻擊命中你時，你可以使用你的反應對攻擊者造成 {@damage 1d6} 點心靈傷害。",
"When the morningstar reaches an exalted state, it gains the following properties:": RS("釘頭錘", "昇華"),
"Add {@spell dominate monster} to the list of spells that can be cast from the morningstar.": "將{@spell dominate monster}加入可從釘頭錘施展的法術清單。",
"The saving throw DC for spells cast from the morningstar, as well as for creatures to avoid being {@condition frightened} by it, increases to 17.": "從釘頭錘施展之法術的豁免 DC，以及生物避免被它{@condition frightened}的豁免 DC，提升至 17。",
"When you use your reaction to deal psychic damage to a creature that hits you with a melee attack, the amount of psychic damage increases to {@damage 2d6}.": "當你使用反應對以近戰攻擊命中你的生物造成心靈傷害時，心靈傷害提升至 {@damage 2d6}。",
"While wearing the Verminshroud in its awakened state, you gain the following benefits:": "在覺醒狀態下穿著蟲鼠斗篷時，你獲得以下益處：",
"You can use an action to cast the {@spell insect plague} spell (save {@dc 15}) from the Verminshroud, requiring no material components. This property can't be used again until the next dawn.": "你可以使用一個動作從蟲鼠斗篷施展{@spell insect plague}法術（豁免 {@dc 15}），不需要材料構材。此屬性在下一個黎明之前無法再次使用。",
"When you cast the {@spell polymorph} spell using the Verminshroud, you can transform into a {@creature giant wasp}.": "當你使用蟲鼠斗篷施展{@spell polymorph}法術時，你可以變形為一隻{@creature giant wasp}。",
"While wearing the Verminshroud in its exalted state, you gain the following benefits:": "在昇華狀態下穿著蟲鼠斗篷時，你獲得以下益處：",
"You gain a climbing speed equal to your walking speed.": "你獲得等同於你步行速度的攀爬速度。",
"Your teeth become razor-sharp natural weapons, which you can use to make unarmed strikes. If you hit with them, you deal piercing damage equal to {@dice 1d6} + your Strength modifier, instead of the bludgeoning damage normal for an unarmed strike. You can make this attack as a bonus action. When you bite a creature and deal damage to it, the creature must succeed on a {@dc 17} Constitution saving throw or be {@condition poisoned} for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the condition on itself on a success.": "你的牙齒變為剃刀般鋒利的天生武器，你可以用它們進行徒手打擊。若以它們命中，你造成等於 {@dice 1d6} + 你的力量調整值的穿刺傷害，而非徒手打擊一般造成的鈍擊傷害。你可以使用一個附贈動作進行此攻擊。當你咬中一個生物並對它造成傷害時，該生物必須成功通過一次 {@dc 17} 體質豁免檢定，否則{@condition poisoned} 1 分鐘。目標可以在它每個回合結束時重複豁免檢定，成功時結束自身的狀態。",
"When you cast the {@spell polymorph} spell using the Verminshroud, you can transform into a {@creature giant scorpion}.": "當你使用蟲鼠斗篷施展{@spell polymorph}法術時，你可以變形為一隻{@creature giant scorpion}。",
"When the war pick reaches an awakened state, it gains the following properties:": RS("戰鎬", "覺醒"),
"The saving throw DC for the war pick's Breath Weapon property increases to 15, and that property deals {@damage 4d6} damage on a failed save, or half as much damage on a successful one.": "戰鎬吐息武器屬性的豁免 DC 提升至 15，且該屬性在豁免失敗時造成 {@damage 4d6} 點傷害，成功時傷害減半。",
"The saving throw DC for the war pick's Frightful Presence property increases to 15.": "戰鎬駭人威儀屬性的豁免 DC 提升至 15。",
"While carrying the weapon, you have resistance to acid, cold, fire, lightning, and poison damage.": "攜帶這把武器時，你具有酸蝕、寒冷、火焰、閃電與毒素傷害抗性。",
"When the war pick reaches an exalted state, it gains the following properties:": RS("戰鎬", "昇華"),
"The saving throw DC for the war pick's Breath Weapon property increases to 17, and that property deals {@damage 5d6} damage on a failed save, or half as much damage on a successful one.": "戰鎬吐息武器屬性的豁免 DC 提升至 17，且該屬性在豁免失敗時造成 {@damage 5d6} 點傷害，成功時傷害減半。",
"The saving throw DC for the war pick's Frightful Presence property increases to 17.": "戰鎬駭人威儀屬性的豁免 DC 提升至 17。",
"Once the Wreath of the Prism reaches an awakened state, it gains the following benefits:": "稜彩花冠進入覺醒狀態後，它獲得以下益處：",
"You can affect creatures of challenge rating 10 or lower with the wreath.": "你可以用花冠影響挑戰等級 10 或更低的生物。",
"The save DC of the wreath's spell increases to 15.": "花冠法術的豁免 DC 提升至 15。",
"Once the Wreath of the Prism reaches an exalted state, it gains the following benefits:": "稜彩花冠進入昇華狀態後，它獲得以下益處：",
"You can affect creatures of challenge rating 15 or lower with the wreath.": "你可以用花冠影響挑戰等級 15 或更低的生物。",
"The save DC of the wreath's spell increases to 17.": "花冠法術的豁免 DC 提升至 17。",
});
